// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "Block_proc.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic Block_proc::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic Block_proc::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<4> Block_proc::ap_ST_fsm_state1 = "1";
const sc_lv<4> Block_proc::ap_ST_fsm_state2 = "10";
const sc_lv<4> Block_proc::ap_ST_fsm_state3 = "100";
const sc_lv<4> Block_proc::ap_ST_fsm_state4 = "1000";
const sc_lv<32> Block_proc::ap_const_lv32_0 = "00000000000000000000000000000000";
const bool Block_proc::ap_const_boolean_1 = true;
const sc_lv<1> Block_proc::ap_const_lv1_1 = "1";
const sc_lv<32> Block_proc::ap_const_lv32_3 = "11";
const sc_lv<32> Block_proc::ap_const_lv32_2 = "10";
const sc_lv<1> Block_proc::ap_const_lv1_0 = "0";
const sc_lv<32> Block_proc::ap_const_lv32_1 = "1";
const sc_lv<1024> Block_proc::ap_const_lv1024_lc_2 = "1000000000000000000";
const sc_lv<1024> Block_proc::ap_const_lv1024_lc_1 = "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";

Block_proc::Block_proc(sc_module_name name) : sc_module(name), mVcdFile(0) {
    regslice_both_out_data_V_U = new regslice_both<1024>("regslice_both_out_data_V_U");
    regslice_both_out_data_V_U->ap_clk(ap_clk);
    regslice_both_out_data_V_U->ap_rst(ap_rst);
    regslice_both_out_data_V_U->data_in(out_r_TDATA_int);
    regslice_both_out_data_V_U->vld_in(out_r_TVALID_int);
    regslice_both_out_data_V_U->ack_in(out_r_TREADY_int);
    regslice_both_out_data_V_U->data_out(out_r_TDATA);
    regslice_both_out_data_V_U->vld_out(regslice_both_out_data_V_U_vld_out);
    regslice_both_out_data_V_U->ack_out(out_r_TREADY);
    regslice_both_out_data_V_U->apdone_blk(regslice_both_out_data_V_U_apdone_blk);
    regslice_both_out_last_V_U = new regslice_both<1>("regslice_both_out_last_V_U");
    regslice_both_out_last_V_U->ap_clk(ap_clk);
    regslice_both_out_last_V_U->ap_rst(ap_rst);
    regslice_both_out_last_V_U->data_in(out_r_TLAST_int);
    regslice_both_out_last_V_U->vld_in(out_r_TVALID_int);
    regslice_both_out_last_V_U->ack_in(regslice_both_out_last_V_U_ack_in_dummy);
    regslice_both_out_last_V_U->data_out(out_r_TLAST);
    regslice_both_out_last_V_U->vld_out(regslice_both_out_last_V_U_vld_out);
    regslice_both_out_last_V_U->ack_out(out_r_TREADY);
    regslice_both_out_last_V_U->apdone_blk(regslice_both_out_last_V_U_apdone_blk);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_state1);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( should_skip_0_loc_empty_n );
    sensitive << ( val_assign_loc_empty_n );
    sensitive << ( io_acc_block_signal_op12 );

    SC_METHOD(thread_ap_block_state1_io);
    sensitive << ( should_skip_0_loc_dout );
    sensitive << ( out_r_TREADY_int );

    SC_METHOD(thread_ap_block_state3_io);
    sensitive << ( should_skip_0_loc_read_reg_88 );
    sensitive << ( out_r_TREADY_int );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( regslice_both_out_data_V_U_apdone_blk );
    sensitive << ( ap_block_state3_io );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( regslice_both_out_data_V_U_apdone_blk );
    sensitive << ( ap_block_state3_io );

    SC_METHOD(thread_io_acc_block_signal_op12);
    sensitive << ( out_local_V_data_0_V_empty_n );
    sensitive << ( out_local_V_data_1_V_empty_n );

    SC_METHOD(thread_out_local_V_data_0_V_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( out_local_V_data_0_V_empty_n );

    SC_METHOD(thread_out_local_V_data_0_V_read);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( should_skip_0_loc_empty_n );
    sensitive << ( val_assign_loc_empty_n );
    sensitive << ( io_acc_block_signal_op12 );
    sensitive << ( ap_block_state1_io );

    SC_METHOD(thread_out_local_V_data_1_V_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( out_local_V_data_1_V_empty_n );

    SC_METHOD(thread_out_local_V_data_1_V_read);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( should_skip_0_loc_empty_n );
    sensitive << ( val_assign_loc_empty_n );
    sensitive << ( io_acc_block_signal_op12 );
    sensitive << ( ap_block_state1_io );

    SC_METHOD(thread_out_r_TDATA_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( should_skip_0_loc_dout );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( should_skip_0_loc_read_reg_88 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( out_r_TREADY_int );

    SC_METHOD(thread_out_r_TDATA_int);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( out_local_V_data_0_V_dout );
    sensitive << ( should_skip_0_loc_dout );
    sensitive << ( should_skip_0_loc_empty_n );
    sensitive << ( val_assign_loc_empty_n );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( io_acc_block_signal_op12 );
    sensitive << ( tmp_data_1_V_reg_102 );

    SC_METHOD(thread_out_r_TLAST_int);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( should_skip_0_loc_dout );
    sensitive << ( should_skip_0_loc_empty_n );
    sensitive << ( val_assign_loc_empty_n );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( io_acc_block_signal_op12 );
    sensitive << ( val_assign_loc_read_reg_92 );

    SC_METHOD(thread_out_r_TVALID);
    sensitive << ( regslice_both_out_data_V_U_vld_out );

    SC_METHOD(thread_out_r_TVALID_int);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( should_skip_0_loc_dout );
    sensitive << ( should_skip_0_loc_empty_n );
    sensitive << ( val_assign_loc_empty_n );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( io_acc_block_signal_op12 );
    sensitive << ( ap_block_state1_io );
    sensitive << ( out_r_TREADY_int );

    SC_METHOD(thread_should_skip_0_loc_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( should_skip_0_loc_empty_n );

    SC_METHOD(thread_should_skip_0_loc_read);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( should_skip_0_loc_empty_n );
    sensitive << ( val_assign_loc_empty_n );
    sensitive << ( io_acc_block_signal_op12 );
    sensitive << ( ap_block_state1_io );

    SC_METHOD(thread_val_assign_loc_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( val_assign_loc_empty_n );

    SC_METHOD(thread_val_assign_loc_read);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( should_skip_0_loc_empty_n );
    sensitive << ( val_assign_loc_empty_n );
    sensitive << ( io_acc_block_signal_op12 );
    sensitive << ( ap_block_state1_io );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( should_skip_0_loc_dout );
    sensitive << ( should_skip_0_loc_empty_n );
    sensitive << ( val_assign_loc_empty_n );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( io_acc_block_signal_op12 );
    sensitive << ( ap_block_state1_io );
    sensitive << ( regslice_both_out_data_V_U_apdone_blk );
    sensitive << ( ap_block_state3_io );
    sensitive << ( out_r_TREADY_int );

    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "0001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "Block_proc_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, out_local_V_data_0_V_dout, "(port)out_local_V_data_0_V_dout");
    sc_trace(mVcdFile, out_local_V_data_0_V_empty_n, "(port)out_local_V_data_0_V_empty_n");
    sc_trace(mVcdFile, out_local_V_data_0_V_read, "(port)out_local_V_data_0_V_read");
    sc_trace(mVcdFile, out_local_V_data_1_V_dout, "(port)out_local_V_data_1_V_dout");
    sc_trace(mVcdFile, out_local_V_data_1_V_empty_n, "(port)out_local_V_data_1_V_empty_n");
    sc_trace(mVcdFile, out_local_V_data_1_V_read, "(port)out_local_V_data_1_V_read");
    sc_trace(mVcdFile, should_skip_0_loc_dout, "(port)should_skip_0_loc_dout");
    sc_trace(mVcdFile, should_skip_0_loc_empty_n, "(port)should_skip_0_loc_empty_n");
    sc_trace(mVcdFile, should_skip_0_loc_read, "(port)should_skip_0_loc_read");
    sc_trace(mVcdFile, out_r_TDATA, "(port)out_r_TDATA");
    sc_trace(mVcdFile, out_r_TVALID, "(port)out_r_TVALID");
    sc_trace(mVcdFile, out_r_TREADY, "(port)out_r_TREADY");
    sc_trace(mVcdFile, out_r_TLAST, "(port)out_r_TLAST");
    sc_trace(mVcdFile, val_assign_loc_dout, "(port)val_assign_loc_dout");
    sc_trace(mVcdFile, val_assign_loc_empty_n, "(port)val_assign_loc_empty_n");
    sc_trace(mVcdFile, val_assign_loc_read, "(port)val_assign_loc_read");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, out_local_V_data_0_V_blk_n, "out_local_V_data_0_V_blk_n");
    sc_trace(mVcdFile, out_local_V_data_1_V_blk_n, "out_local_V_data_1_V_blk_n");
    sc_trace(mVcdFile, should_skip_0_loc_blk_n, "should_skip_0_loc_blk_n");
    sc_trace(mVcdFile, out_r_TDATA_blk_n, "out_r_TDATA_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, should_skip_0_loc_read_reg_88, "should_skip_0_loc_read_reg_88");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, val_assign_loc_blk_n, "val_assign_loc_blk_n");
    sc_trace(mVcdFile, io_acc_block_signal_op12, "io_acc_block_signal_op12");
    sc_trace(mVcdFile, ap_block_state1, "ap_block_state1");
    sc_trace(mVcdFile, ap_block_state1_io, "ap_block_state1_io");
    sc_trace(mVcdFile, val_assign_loc_read_reg_92, "val_assign_loc_read_reg_92");
    sc_trace(mVcdFile, tmp_data_1_V_reg_102, "tmp_data_1_V_reg_102");
    sc_trace(mVcdFile, regslice_both_out_data_V_U_apdone_blk, "regslice_both_out_data_V_U_apdone_blk");
    sc_trace(mVcdFile, ap_block_state3_io, "ap_block_state3_io");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, out_r_TDATA_int, "out_r_TDATA_int");
    sc_trace(mVcdFile, out_r_TVALID_int, "out_r_TVALID_int");
    sc_trace(mVcdFile, out_r_TREADY_int, "out_r_TREADY_int");
    sc_trace(mVcdFile, regslice_both_out_data_V_U_vld_out, "regslice_both_out_data_V_U_vld_out");
    sc_trace(mVcdFile, regslice_both_out_last_V_U_apdone_blk, "regslice_both_out_last_V_U_apdone_blk");
    sc_trace(mVcdFile, out_r_TLAST_int, "out_r_TLAST_int");
    sc_trace(mVcdFile, regslice_both_out_last_V_U_ack_in_dummy, "regslice_both_out_last_V_U_ack_in_dummy");
    sc_trace(mVcdFile, regslice_both_out_last_V_U_vld_out, "regslice_both_out_last_V_U_vld_out");
#endif

    }
}

Block_proc::~Block_proc() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete regslice_both_out_data_V_U;
    delete regslice_both_out_last_V_U;
}

void Block_proc::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                    !(esl_seteq<1,1,1>(ap_const_logic_1, regslice_both_out_data_V_U_apdone_blk.read()) || esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state3_io.read())))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, should_skip_0_loc_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, val_assign_loc_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op12.read()) || esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state1_io.read())))) {
        should_skip_0_loc_read_reg_88 = should_skip_0_loc_dout.read();
        tmp_data_1_V_reg_102 = out_local_V_data_1_V_dout.read();
        val_assign_loc_read_reg_92 = val_assign_loc_dout.read();
    }
}

void Block_proc::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void Block_proc::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void Block_proc::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void Block_proc::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void Block_proc::thread_ap_block_state1() {
    ap_block_state1 = (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, should_skip_0_loc_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, val_assign_loc_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op12.read()));
}

void Block_proc::thread_ap_block_state1_io() {
    ap_block_state1_io = ((esl_seteq<1,1,1>(should_skip_0_loc_dout.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, out_r_TREADY_int.read())) || (esl_seteq<1,1,1>(should_skip_0_loc_dout.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_const_logic_0, out_r_TREADY_int.read())));
}

void Block_proc::thread_ap_block_state3_io() {
    ap_block_state3_io = ((esl_seteq<1,1,1>(should_skip_0_loc_read_reg_88.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, out_r_TREADY_int.read())) || (esl_seteq<1,1,1>(ap_const_lv1_1, should_skip_0_loc_read_reg_88.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, out_r_TREADY_int.read())));
}

void Block_proc::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_1, regslice_both_out_data_V_U_apdone_blk.read()) || esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state3_io.read())))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_done_reg.read();
    }
}

void Block_proc::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void Block_proc::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_1, regslice_both_out_data_V_U_apdone_blk.read()) || esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state3_io.read())))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void Block_proc::thread_io_acc_block_signal_op12() {
    io_acc_block_signal_op12 = (out_local_V_data_0_V_empty_n.read() & out_local_V_data_1_V_empty_n.read());
}

void Block_proc::thread_out_local_V_data_0_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        out_local_V_data_0_V_blk_n = out_local_V_data_0_V_empty_n.read();
    } else {
        out_local_V_data_0_V_blk_n = ap_const_logic_1;
    }
}

void Block_proc::thread_out_local_V_data_0_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, should_skip_0_loc_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, val_assign_loc_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op12.read()) || esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state1_io.read())))) {
        out_local_V_data_0_V_read = ap_const_logic_1;
    } else {
        out_local_V_data_0_V_read = ap_const_logic_0;
    }
}

void Block_proc::thread_out_local_V_data_1_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        out_local_V_data_1_V_blk_n = out_local_V_data_1_V_empty_n.read();
    } else {
        out_local_V_data_1_V_blk_n = ap_const_logic_1;
    }
}

void Block_proc::thread_out_local_V_data_1_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, should_skip_0_loc_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, val_assign_loc_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op12.read()) || esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state1_io.read())))) {
        out_local_V_data_1_V_read = ap_const_logic_1;
    } else {
        out_local_V_data_1_V_read = ap_const_logic_0;
    }
}

void Block_proc::thread_out_r_TDATA_blk_n() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
          !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
          esl_seteq<1,1,1>(should_skip_0_loc_dout.read(), ap_const_lv1_1)) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, should_skip_0_loc_read_reg_88.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
          !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
          esl_seteq<1,1,1>(should_skip_0_loc_dout.read(), ap_const_lv1_0)) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
          esl_seteq<1,1,1>(should_skip_0_loc_read_reg_88.read(), ap_const_lv1_0)))) {
        out_r_TDATA_blk_n = out_r_TREADY_int.read();
    } else {
        out_r_TDATA_blk_n = ap_const_logic_1;
    }
}

void Block_proc::thread_out_r_TDATA_int() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        out_r_TDATA_int = ap_const_lv1024_lc_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        out_r_TDATA_int = tmp_data_1_V_reg_102.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(should_skip_0_loc_dout.read(), ap_const_lv1_1) && 
                !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, should_skip_0_loc_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, val_assign_loc_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op12.read())))) {
        out_r_TDATA_int = ap_const_lv1024_lc_2;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(should_skip_0_loc_dout.read(), ap_const_lv1_0) && 
                !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, should_skip_0_loc_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, val_assign_loc_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op12.read())))) {
        out_r_TDATA_int = out_local_V_data_0_V_dout.read();
    } else {
        out_r_TDATA_int = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    }
}

void Block_proc::thread_out_r_TLAST_int() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
        out_r_TLAST_int = val_assign_loc_read_reg_92.read();
    } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                 esl_seteq<1,1,1>(should_skip_0_loc_dout.read(), ap_const_lv1_0) && 
                 !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, should_skip_0_loc_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, val_assign_loc_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op12.read()))) || 
                (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                 esl_seteq<1,1,1>(should_skip_0_loc_dout.read(), ap_const_lv1_1) && 
                 !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, should_skip_0_loc_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, val_assign_loc_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op12.read()))))) {
        out_r_TLAST_int = ap_const_lv1_0;
    } else {
        out_r_TLAST_int =  (sc_lv<1>) ("X");
    }
}

void Block_proc::thread_out_r_TVALID() {
    out_r_TVALID = regslice_both_out_data_V_U_vld_out.read();
}

void Block_proc::thread_out_r_TVALID_int() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
          esl_seteq<1,1,1>(should_skip_0_loc_dout.read(), ap_const_lv1_0) && 
          !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, should_skip_0_loc_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, val_assign_loc_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op12.read()) || esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state1_io.read()))) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
          esl_seteq<1,1,1>(should_skip_0_loc_dout.read(), ap_const_lv1_1) && 
          !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, should_skip_0_loc_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, val_assign_loc_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op12.read()) || esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state1_io.read()))) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,1,1>(out_r_TREADY_int.read(), ap_const_logic_1)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
          esl_seteq<1,1,1>(out_r_TREADY_int.read(), ap_const_logic_1)))) {
        out_r_TVALID_int = ap_const_logic_1;
    } else {
        out_r_TVALID_int = ap_const_logic_0;
    }
}

void Block_proc::thread_should_skip_0_loc_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        should_skip_0_loc_blk_n = should_skip_0_loc_empty_n.read();
    } else {
        should_skip_0_loc_blk_n = ap_const_logic_1;
    }
}

void Block_proc::thread_should_skip_0_loc_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, should_skip_0_loc_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, val_assign_loc_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op12.read()) || esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state1_io.read())))) {
        should_skip_0_loc_read = ap_const_logic_1;
    } else {
        should_skip_0_loc_read = ap_const_logic_0;
    }
}

void Block_proc::thread_val_assign_loc_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        val_assign_loc_blk_n = val_assign_loc_empty_n.read();
    } else {
        val_assign_loc_blk_n = ap_const_logic_1;
    }
}

void Block_proc::thread_val_assign_loc_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, should_skip_0_loc_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, val_assign_loc_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op12.read()) || esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state1_io.read())))) {
        val_assign_loc_read = ap_const_logic_1;
    } else {
        val_assign_loc_read = ap_const_logic_0;
    }
}

void Block_proc::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(should_skip_0_loc_dout.read(), ap_const_lv1_1) && !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, should_skip_0_loc_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, val_assign_loc_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op12.read()) || esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state1_io.read())))) {
                ap_NS_fsm = ap_ST_fsm_state4;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(should_skip_0_loc_dout.read(), ap_const_lv1_0) && !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, should_skip_0_loc_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, val_assign_loc_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op12.read()) || esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state1_io.read())))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(out_r_TREADY_int.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state2;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && !(esl_seteq<1,1,1>(ap_const_logic_1, regslice_both_out_data_V_U_apdone_blk.read()) || esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state3_io.read())))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(out_r_TREADY_int.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        default : 
            ap_NS_fsm =  (sc_lv<4>) ("XXXX");
            break;
    }
}

}

