// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config13_s.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config13_s::ap_const_logic_1 = sc_dt::Log_1;
const bool dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config13_s::ap_const_boolean_1 = true;
const sc_lv<5> dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config13_s::ap_const_lv5_0 = "00000";
const sc_lv<32> dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config13_s::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config13_s::ap_const_lv32_5 = "101";
const sc_lv<32> dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config13_s::ap_const_lv32_1F = "11111";
const sc_lv<27> dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config13_s::ap_const_lv27_A000 = "1010000000000000";
const sc_lv<27> dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config13_s::ap_const_lv27_7FF6000 = "111111111110110000000000000";
const sc_logic dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config13_s::ap_const_logic_0 = sc_dt::Log_0;

dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config13_s::dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config13_s(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_acc_1_V_fu_462_p2);
    sensitive << ( add_ln703_9_fu_438_p2 );
    sensitive << ( add_ln703_12_fu_456_p2 );

    SC_METHOD(thread_add_ln703_10_fu_444_p2);
    sensitive << ( trunc_ln708_11_fu_400_p4 );
    sensitive << ( trunc_ln708_10_fu_384_p4 );

    SC_METHOD(thread_add_ln703_11_fu_450_p2);
    sensitive << ( trunc_ln708_12_fu_416_p4 );

    SC_METHOD(thread_add_ln703_12_fu_456_p2);
    sensitive << ( add_ln703_10_fu_444_p2 );
    sensitive << ( add_ln703_11_fu_450_p2 );

    SC_METHOD(thread_add_ln703_1_fu_278_p2);
    sensitive << ( trunc_ln708_2_fu_178_p4 );
    sensitive << ( trunc_ln708_1_fu_150_p4 );

    SC_METHOD(thread_add_ln703_2_fu_284_p2);
    sensitive << ( add_ln703_fu_272_p2 );
    sensitive << ( add_ln703_1_fu_278_p2 );

    SC_METHOD(thread_add_ln703_3_fu_290_p2);
    sensitive << ( trunc_ln708_4_fu_234_p4 );
    sensitive << ( trunc_ln708_3_fu_206_p4 );

    SC_METHOD(thread_add_ln703_4_fu_296_p2);
    sensitive << ( trunc_ln708_5_fu_262_p4 );

    SC_METHOD(thread_add_ln703_5_fu_302_p2);
    sensitive << ( add_ln703_3_fu_290_p2 );
    sensitive << ( add_ln703_4_fu_296_p2 );

    SC_METHOD(thread_add_ln703_6_fu_308_p2);
    sensitive << ( add_ln703_2_fu_284_p2 );
    sensitive << ( add_ln703_5_fu_302_p2 );

    SC_METHOD(thread_add_ln703_7_fu_426_p2);
    sensitive << ( trunc_ln708_7_fu_336_p4 );
    sensitive << ( trunc_ln708_6_fu_320_p4 );

    SC_METHOD(thread_add_ln703_8_fu_432_p2);
    sensitive << ( trunc_ln708_9_fu_368_p4 );
    sensitive << ( trunc_ln708_8_fu_352_p4 );

    SC_METHOD(thread_add_ln703_9_fu_438_p2);
    sensitive << ( add_ln703_7_fu_426_p2 );
    sensitive << ( add_ln703_8_fu_432_p2 );

    SC_METHOD(thread_add_ln703_fu_272_p2);
    sensitive << ( trunc_ln708_s_fu_122_p4 );
    sensitive << ( trunc_ln_fu_94_p4 );

    SC_METHOD(thread_ap_ready);

    SC_METHOD(thread_ap_return_0);
    sensitive << ( add_ln703_6_fu_308_p2 );

    SC_METHOD(thread_ap_return_1);
    sensitive << ( acc_1_V_fu_462_p2 );

    SC_METHOD(thread_sext_ln1118_1_fu_104_p0);
    sensitive << ( data_4_V_read );

    SC_METHOD(thread_sext_ln1118_1_fu_104_p1);
    sensitive << ( sext_ln1118_1_fu_104_p0 );

    SC_METHOD(thread_sext_ln1118_2_fu_132_p0);
    sensitive << ( data_6_V_read );

    SC_METHOD(thread_sext_ln1118_2_fu_132_p1);
    sensitive << ( sext_ln1118_2_fu_132_p0 );

    SC_METHOD(thread_sext_ln1118_3_fu_160_p0);
    sensitive << ( data_7_V_read );

    SC_METHOD(thread_sext_ln1118_3_fu_160_p1);
    sensitive << ( sext_ln1118_3_fu_160_p0 );

    SC_METHOD(thread_sext_ln1118_4_fu_188_p0);
    sensitive << ( data_8_V_read );

    SC_METHOD(thread_sext_ln1118_4_fu_188_p1);
    sensitive << ( sext_ln1118_4_fu_188_p0 );

    SC_METHOD(thread_sext_ln1118_5_fu_216_p0);
    sensitive << ( data_9_V_read );

    SC_METHOD(thread_sext_ln1118_5_fu_216_p1);
    sensitive << ( sext_ln1118_5_fu_216_p0 );

    SC_METHOD(thread_sext_ln1118_6_fu_244_p0);
    sensitive << ( data_10_V_read );

    SC_METHOD(thread_sext_ln1118_6_fu_244_p1);
    sensitive << ( sext_ln1118_6_fu_244_p0 );

    SC_METHOD(thread_sext_ln1118_fu_76_p0);
    sensitive << ( data_2_V_read );

    SC_METHOD(thread_sext_ln1118_fu_76_p1);
    sensitive << ( sext_ln1118_fu_76_p0 );

    SC_METHOD(thread_shl_ln1118_1_fu_136_p1);
    sensitive << ( data_6_V_read );

    SC_METHOD(thread_shl_ln1118_1_fu_136_p3);
    sensitive << ( shl_ln1118_1_fu_136_p1 );

    SC_METHOD(thread_shl_ln1118_2_fu_164_p1);
    sensitive << ( data_7_V_read );

    SC_METHOD(thread_shl_ln1118_2_fu_164_p3);
    sensitive << ( shl_ln1118_2_fu_164_p1 );

    SC_METHOD(thread_shl_ln1118_3_fu_192_p1);
    sensitive << ( data_8_V_read );

    SC_METHOD(thread_shl_ln1118_3_fu_192_p3);
    sensitive << ( shl_ln1118_3_fu_192_p1 );

    SC_METHOD(thread_shl_ln1118_4_fu_220_p1);
    sensitive << ( data_9_V_read );

    SC_METHOD(thread_shl_ln1118_4_fu_220_p3);
    sensitive << ( shl_ln1118_4_fu_220_p1 );

    SC_METHOD(thread_shl_ln1118_5_fu_248_p1);
    sensitive << ( data_10_V_read );

    SC_METHOD(thread_shl_ln1118_5_fu_248_p3);
    sensitive << ( shl_ln1118_5_fu_248_p1 );

    SC_METHOD(thread_shl_ln1118_s_fu_108_p1);
    sensitive << ( data_4_V_read );

    SC_METHOD(thread_shl_ln1118_s_fu_108_p3);
    sensitive << ( shl_ln1118_s_fu_108_p1 );

    SC_METHOD(thread_shl_ln_fu_80_p1);
    sensitive << ( data_2_V_read );

    SC_METHOD(thread_shl_ln_fu_80_p3);
    sensitive << ( shl_ln_fu_80_p1 );

    SC_METHOD(thread_sub_ln1118_10_fu_362_p2);
    sensitive << ( shl_ln1118_2_fu_164_p3 );

    SC_METHOD(thread_sub_ln1118_11_fu_378_p2);
    sensitive << ( shl_ln1118_3_fu_192_p3 );

    SC_METHOD(thread_sub_ln1118_12_fu_394_p2);
    sensitive << ( shl_ln1118_4_fu_220_p3 );

    SC_METHOD(thread_sub_ln1118_13_fu_410_p2);
    sensitive << ( shl_ln1118_5_fu_248_p3 );

    SC_METHOD(thread_sub_ln1118_1_fu_116_p2);
    sensitive << ( shl_ln1118_s_fu_108_p3 );
    sensitive << ( sext_ln1118_1_fu_104_p1 );

    SC_METHOD(thread_sub_ln1118_2_fu_144_p2);
    sensitive << ( shl_ln1118_1_fu_136_p3 );

    SC_METHOD(thread_sub_ln1118_3_fu_172_p2);
    sensitive << ( shl_ln1118_2_fu_164_p3 );
    sensitive << ( sext_ln1118_3_fu_160_p1 );

    SC_METHOD(thread_sub_ln1118_4_fu_200_p2);
    sensitive << ( shl_ln1118_3_fu_192_p3 );
    sensitive << ( sext_ln1118_4_fu_188_p1 );

    SC_METHOD(thread_sub_ln1118_5_fu_228_p2);
    sensitive << ( shl_ln1118_4_fu_220_p3 );
    sensitive << ( sext_ln1118_5_fu_216_p1 );

    SC_METHOD(thread_sub_ln1118_6_fu_256_p2);
    sensitive << ( shl_ln1118_5_fu_248_p3 );
    sensitive << ( sext_ln1118_6_fu_244_p1 );

    SC_METHOD(thread_sub_ln1118_7_fu_314_p2);
    sensitive << ( shl_ln_fu_80_p3 );
    sensitive << ( sext_ln1118_fu_76_p1 );

    SC_METHOD(thread_sub_ln1118_8_fu_330_p2);
    sensitive << ( shl_ln1118_s_fu_108_p3 );

    SC_METHOD(thread_sub_ln1118_9_fu_346_p2);
    sensitive << ( shl_ln1118_1_fu_136_p3 );
    sensitive << ( sext_ln1118_2_fu_132_p1 );

    SC_METHOD(thread_sub_ln1118_fu_88_p2);
    sensitive << ( shl_ln_fu_80_p3 );

    SC_METHOD(thread_trunc_ln708_10_fu_384_p4);
    sensitive << ( sub_ln1118_11_fu_378_p2 );

    SC_METHOD(thread_trunc_ln708_11_fu_400_p4);
    sensitive << ( sub_ln1118_12_fu_394_p2 );

    SC_METHOD(thread_trunc_ln708_12_fu_416_p4);
    sensitive << ( sub_ln1118_13_fu_410_p2 );

    SC_METHOD(thread_trunc_ln708_1_fu_150_p4);
    sensitive << ( sub_ln1118_2_fu_144_p2 );

    SC_METHOD(thread_trunc_ln708_2_fu_178_p4);
    sensitive << ( sub_ln1118_3_fu_172_p2 );

    SC_METHOD(thread_trunc_ln708_3_fu_206_p4);
    sensitive << ( sub_ln1118_4_fu_200_p2 );

    SC_METHOD(thread_trunc_ln708_4_fu_234_p4);
    sensitive << ( sub_ln1118_5_fu_228_p2 );

    SC_METHOD(thread_trunc_ln708_5_fu_262_p4);
    sensitive << ( sub_ln1118_6_fu_256_p2 );

    SC_METHOD(thread_trunc_ln708_6_fu_320_p4);
    sensitive << ( sub_ln1118_7_fu_314_p2 );

    SC_METHOD(thread_trunc_ln708_7_fu_336_p4);
    sensitive << ( sub_ln1118_8_fu_330_p2 );

    SC_METHOD(thread_trunc_ln708_8_fu_352_p4);
    sensitive << ( sub_ln1118_9_fu_346_p2 );

    SC_METHOD(thread_trunc_ln708_9_fu_368_p4);
    sensitive << ( sub_ln1118_10_fu_362_p2 );

    SC_METHOD(thread_trunc_ln708_s_fu_122_p4);
    sensitive << ( sub_ln1118_1_fu_116_p2 );

    SC_METHOD(thread_trunc_ln_fu_94_p4);
    sensitive << ( sub_ln1118_fu_88_p2 );

    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config13_s_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, data_2_V_read, "(port)data_2_V_read");
    sc_trace(mVcdFile, data_4_V_read, "(port)data_4_V_read");
    sc_trace(mVcdFile, data_6_V_read, "(port)data_6_V_read");
    sc_trace(mVcdFile, data_7_V_read, "(port)data_7_V_read");
    sc_trace(mVcdFile, data_8_V_read, "(port)data_8_V_read");
    sc_trace(mVcdFile, data_9_V_read, "(port)data_9_V_read");
    sc_trace(mVcdFile, data_10_V_read, "(port)data_10_V_read");
    sc_trace(mVcdFile, ap_return_0, "(port)ap_return_0");
    sc_trace(mVcdFile, ap_return_1, "(port)ap_return_1");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, sext_ln1118_fu_76_p0, "sext_ln1118_fu_76_p0");
    sc_trace(mVcdFile, shl_ln_fu_80_p1, "shl_ln_fu_80_p1");
    sc_trace(mVcdFile, shl_ln_fu_80_p3, "shl_ln_fu_80_p3");
    sc_trace(mVcdFile, sub_ln1118_fu_88_p2, "sub_ln1118_fu_88_p2");
    sc_trace(mVcdFile, sext_ln1118_1_fu_104_p0, "sext_ln1118_1_fu_104_p0");
    sc_trace(mVcdFile, shl_ln1118_s_fu_108_p1, "shl_ln1118_s_fu_108_p1");
    sc_trace(mVcdFile, shl_ln1118_s_fu_108_p3, "shl_ln1118_s_fu_108_p3");
    sc_trace(mVcdFile, sext_ln1118_1_fu_104_p1, "sext_ln1118_1_fu_104_p1");
    sc_trace(mVcdFile, sub_ln1118_1_fu_116_p2, "sub_ln1118_1_fu_116_p2");
    sc_trace(mVcdFile, sext_ln1118_2_fu_132_p0, "sext_ln1118_2_fu_132_p0");
    sc_trace(mVcdFile, shl_ln1118_1_fu_136_p1, "shl_ln1118_1_fu_136_p1");
    sc_trace(mVcdFile, shl_ln1118_1_fu_136_p3, "shl_ln1118_1_fu_136_p3");
    sc_trace(mVcdFile, sub_ln1118_2_fu_144_p2, "sub_ln1118_2_fu_144_p2");
    sc_trace(mVcdFile, sext_ln1118_3_fu_160_p0, "sext_ln1118_3_fu_160_p0");
    sc_trace(mVcdFile, shl_ln1118_2_fu_164_p1, "shl_ln1118_2_fu_164_p1");
    sc_trace(mVcdFile, shl_ln1118_2_fu_164_p3, "shl_ln1118_2_fu_164_p3");
    sc_trace(mVcdFile, sext_ln1118_3_fu_160_p1, "sext_ln1118_3_fu_160_p1");
    sc_trace(mVcdFile, sub_ln1118_3_fu_172_p2, "sub_ln1118_3_fu_172_p2");
    sc_trace(mVcdFile, sext_ln1118_4_fu_188_p0, "sext_ln1118_4_fu_188_p0");
    sc_trace(mVcdFile, shl_ln1118_3_fu_192_p1, "shl_ln1118_3_fu_192_p1");
    sc_trace(mVcdFile, shl_ln1118_3_fu_192_p3, "shl_ln1118_3_fu_192_p3");
    sc_trace(mVcdFile, sext_ln1118_4_fu_188_p1, "sext_ln1118_4_fu_188_p1");
    sc_trace(mVcdFile, sub_ln1118_4_fu_200_p2, "sub_ln1118_4_fu_200_p2");
    sc_trace(mVcdFile, sext_ln1118_5_fu_216_p0, "sext_ln1118_5_fu_216_p0");
    sc_trace(mVcdFile, shl_ln1118_4_fu_220_p1, "shl_ln1118_4_fu_220_p1");
    sc_trace(mVcdFile, shl_ln1118_4_fu_220_p3, "shl_ln1118_4_fu_220_p3");
    sc_trace(mVcdFile, sext_ln1118_5_fu_216_p1, "sext_ln1118_5_fu_216_p1");
    sc_trace(mVcdFile, sub_ln1118_5_fu_228_p2, "sub_ln1118_5_fu_228_p2");
    sc_trace(mVcdFile, sext_ln1118_6_fu_244_p0, "sext_ln1118_6_fu_244_p0");
    sc_trace(mVcdFile, shl_ln1118_5_fu_248_p1, "shl_ln1118_5_fu_248_p1");
    sc_trace(mVcdFile, shl_ln1118_5_fu_248_p3, "shl_ln1118_5_fu_248_p3");
    sc_trace(mVcdFile, sext_ln1118_6_fu_244_p1, "sext_ln1118_6_fu_244_p1");
    sc_trace(mVcdFile, sub_ln1118_6_fu_256_p2, "sub_ln1118_6_fu_256_p2");
    sc_trace(mVcdFile, trunc_ln708_s_fu_122_p4, "trunc_ln708_s_fu_122_p4");
    sc_trace(mVcdFile, trunc_ln_fu_94_p4, "trunc_ln_fu_94_p4");
    sc_trace(mVcdFile, trunc_ln708_2_fu_178_p4, "trunc_ln708_2_fu_178_p4");
    sc_trace(mVcdFile, trunc_ln708_1_fu_150_p4, "trunc_ln708_1_fu_150_p4");
    sc_trace(mVcdFile, add_ln703_fu_272_p2, "add_ln703_fu_272_p2");
    sc_trace(mVcdFile, add_ln703_1_fu_278_p2, "add_ln703_1_fu_278_p2");
    sc_trace(mVcdFile, trunc_ln708_4_fu_234_p4, "trunc_ln708_4_fu_234_p4");
    sc_trace(mVcdFile, trunc_ln708_3_fu_206_p4, "trunc_ln708_3_fu_206_p4");
    sc_trace(mVcdFile, trunc_ln708_5_fu_262_p4, "trunc_ln708_5_fu_262_p4");
    sc_trace(mVcdFile, add_ln703_3_fu_290_p2, "add_ln703_3_fu_290_p2");
    sc_trace(mVcdFile, add_ln703_4_fu_296_p2, "add_ln703_4_fu_296_p2");
    sc_trace(mVcdFile, add_ln703_2_fu_284_p2, "add_ln703_2_fu_284_p2");
    sc_trace(mVcdFile, add_ln703_5_fu_302_p2, "add_ln703_5_fu_302_p2");
    sc_trace(mVcdFile, sext_ln1118_fu_76_p1, "sext_ln1118_fu_76_p1");
    sc_trace(mVcdFile, sub_ln1118_7_fu_314_p2, "sub_ln1118_7_fu_314_p2");
    sc_trace(mVcdFile, sub_ln1118_8_fu_330_p2, "sub_ln1118_8_fu_330_p2");
    sc_trace(mVcdFile, sext_ln1118_2_fu_132_p1, "sext_ln1118_2_fu_132_p1");
    sc_trace(mVcdFile, sub_ln1118_9_fu_346_p2, "sub_ln1118_9_fu_346_p2");
    sc_trace(mVcdFile, sub_ln1118_10_fu_362_p2, "sub_ln1118_10_fu_362_p2");
    sc_trace(mVcdFile, sub_ln1118_11_fu_378_p2, "sub_ln1118_11_fu_378_p2");
    sc_trace(mVcdFile, sub_ln1118_12_fu_394_p2, "sub_ln1118_12_fu_394_p2");
    sc_trace(mVcdFile, sub_ln1118_13_fu_410_p2, "sub_ln1118_13_fu_410_p2");
    sc_trace(mVcdFile, trunc_ln708_7_fu_336_p4, "trunc_ln708_7_fu_336_p4");
    sc_trace(mVcdFile, trunc_ln708_6_fu_320_p4, "trunc_ln708_6_fu_320_p4");
    sc_trace(mVcdFile, trunc_ln708_9_fu_368_p4, "trunc_ln708_9_fu_368_p4");
    sc_trace(mVcdFile, trunc_ln708_8_fu_352_p4, "trunc_ln708_8_fu_352_p4");
    sc_trace(mVcdFile, add_ln703_7_fu_426_p2, "add_ln703_7_fu_426_p2");
    sc_trace(mVcdFile, add_ln703_8_fu_432_p2, "add_ln703_8_fu_432_p2");
    sc_trace(mVcdFile, trunc_ln708_11_fu_400_p4, "trunc_ln708_11_fu_400_p4");
    sc_trace(mVcdFile, trunc_ln708_10_fu_384_p4, "trunc_ln708_10_fu_384_p4");
    sc_trace(mVcdFile, trunc_ln708_12_fu_416_p4, "trunc_ln708_12_fu_416_p4");
    sc_trace(mVcdFile, add_ln703_10_fu_444_p2, "add_ln703_10_fu_444_p2");
    sc_trace(mVcdFile, add_ln703_11_fu_450_p2, "add_ln703_11_fu_450_p2");
    sc_trace(mVcdFile, add_ln703_9_fu_438_p2, "add_ln703_9_fu_438_p2");
    sc_trace(mVcdFile, add_ln703_12_fu_456_p2, "add_ln703_12_fu_456_p2");
    sc_trace(mVcdFile, add_ln703_6_fu_308_p2, "add_ln703_6_fu_308_p2");
    sc_trace(mVcdFile, acc_1_V_fu_462_p2, "acc_1_V_fu_462_p2");
#endif

    }
}

dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config13_s::~dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config13_s() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config13_s::thread_acc_1_V_fu_462_p2() {
    acc_1_V_fu_462_p2 = (!add_ln703_9_fu_438_p2.read().is_01() || !add_ln703_12_fu_456_p2.read().is_01())? sc_lv<27>(): (sc_biguint<27>(add_ln703_9_fu_438_p2.read()) + sc_biguint<27>(add_ln703_12_fu_456_p2.read()));
}

void dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config13_s::thread_add_ln703_10_fu_444_p2() {
    add_ln703_10_fu_444_p2 = (!trunc_ln708_11_fu_400_p4.read().is_01() || !trunc_ln708_10_fu_384_p4.read().is_01())? sc_lv<27>(): (sc_biguint<27>(trunc_ln708_11_fu_400_p4.read()) + sc_biguint<27>(trunc_ln708_10_fu_384_p4.read()));
}

void dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config13_s::thread_add_ln703_11_fu_450_p2() {
    add_ln703_11_fu_450_p2 = (!trunc_ln708_12_fu_416_p4.read().is_01() || !ap_const_lv27_7FF6000.is_01())? sc_lv<27>(): (sc_biguint<27>(trunc_ln708_12_fu_416_p4.read()) + sc_bigint<27>(ap_const_lv27_7FF6000));
}

void dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config13_s::thread_add_ln703_12_fu_456_p2() {
    add_ln703_12_fu_456_p2 = (!add_ln703_10_fu_444_p2.read().is_01() || !add_ln703_11_fu_450_p2.read().is_01())? sc_lv<27>(): (sc_biguint<27>(add_ln703_10_fu_444_p2.read()) + sc_biguint<27>(add_ln703_11_fu_450_p2.read()));
}

void dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config13_s::thread_add_ln703_1_fu_278_p2() {
    add_ln703_1_fu_278_p2 = (!trunc_ln708_2_fu_178_p4.read().is_01() || !trunc_ln708_1_fu_150_p4.read().is_01())? sc_lv<27>(): (sc_biguint<27>(trunc_ln708_2_fu_178_p4.read()) + sc_biguint<27>(trunc_ln708_1_fu_150_p4.read()));
}

void dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config13_s::thread_add_ln703_2_fu_284_p2() {
    add_ln703_2_fu_284_p2 = (!add_ln703_fu_272_p2.read().is_01() || !add_ln703_1_fu_278_p2.read().is_01())? sc_lv<27>(): (sc_biguint<27>(add_ln703_fu_272_p2.read()) + sc_biguint<27>(add_ln703_1_fu_278_p2.read()));
}

void dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config13_s::thread_add_ln703_3_fu_290_p2() {
    add_ln703_3_fu_290_p2 = (!trunc_ln708_4_fu_234_p4.read().is_01() || !trunc_ln708_3_fu_206_p4.read().is_01())? sc_lv<27>(): (sc_biguint<27>(trunc_ln708_4_fu_234_p4.read()) + sc_biguint<27>(trunc_ln708_3_fu_206_p4.read()));
}

void dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config13_s::thread_add_ln703_4_fu_296_p2() {
    add_ln703_4_fu_296_p2 = (!trunc_ln708_5_fu_262_p4.read().is_01() || !ap_const_lv27_A000.is_01())? sc_lv<27>(): (sc_biguint<27>(trunc_ln708_5_fu_262_p4.read()) + sc_biguint<27>(ap_const_lv27_A000));
}

void dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config13_s::thread_add_ln703_5_fu_302_p2() {
    add_ln703_5_fu_302_p2 = (!add_ln703_3_fu_290_p2.read().is_01() || !add_ln703_4_fu_296_p2.read().is_01())? sc_lv<27>(): (sc_biguint<27>(add_ln703_3_fu_290_p2.read()) + sc_biguint<27>(add_ln703_4_fu_296_p2.read()));
}

void dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config13_s::thread_add_ln703_6_fu_308_p2() {
    add_ln703_6_fu_308_p2 = (!add_ln703_2_fu_284_p2.read().is_01() || !add_ln703_5_fu_302_p2.read().is_01())? sc_lv<27>(): (sc_biguint<27>(add_ln703_2_fu_284_p2.read()) + sc_biguint<27>(add_ln703_5_fu_302_p2.read()));
}

void dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config13_s::thread_add_ln703_7_fu_426_p2() {
    add_ln703_7_fu_426_p2 = (!trunc_ln708_7_fu_336_p4.read().is_01() || !trunc_ln708_6_fu_320_p4.read().is_01())? sc_lv<27>(): (sc_biguint<27>(trunc_ln708_7_fu_336_p4.read()) + sc_biguint<27>(trunc_ln708_6_fu_320_p4.read()));
}

void dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config13_s::thread_add_ln703_8_fu_432_p2() {
    add_ln703_8_fu_432_p2 = (!trunc_ln708_9_fu_368_p4.read().is_01() || !trunc_ln708_8_fu_352_p4.read().is_01())? sc_lv<27>(): (sc_biguint<27>(trunc_ln708_9_fu_368_p4.read()) + sc_biguint<27>(trunc_ln708_8_fu_352_p4.read()));
}

void dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config13_s::thread_add_ln703_9_fu_438_p2() {
    add_ln703_9_fu_438_p2 = (!add_ln703_7_fu_426_p2.read().is_01() || !add_ln703_8_fu_432_p2.read().is_01())? sc_lv<27>(): (sc_biguint<27>(add_ln703_7_fu_426_p2.read()) + sc_biguint<27>(add_ln703_8_fu_432_p2.read()));
}

void dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config13_s::thread_add_ln703_fu_272_p2() {
    add_ln703_fu_272_p2 = (!trunc_ln708_s_fu_122_p4.read().is_01() || !trunc_ln_fu_94_p4.read().is_01())? sc_lv<27>(): (sc_biguint<27>(trunc_ln708_s_fu_122_p4.read()) + sc_biguint<27>(trunc_ln_fu_94_p4.read()));
}

void dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config13_s::thread_ap_ready() {
    ap_ready = ap_const_logic_1;
}

void dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config13_s::thread_ap_return_0() {
    ap_return_0 = add_ln703_6_fu_308_p2.read();
}

void dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config13_s::thread_ap_return_1() {
    ap_return_1 = acc_1_V_fu_462_p2.read();
}

void dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config13_s::thread_sext_ln1118_1_fu_104_p0() {
    sext_ln1118_1_fu_104_p0 = data_4_V_read.read();
}

void dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config13_s::thread_sext_ln1118_1_fu_104_p1() {
    sext_ln1118_1_fu_104_p1 = esl_sext<32,27>(sext_ln1118_1_fu_104_p0.read());
}

void dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config13_s::thread_sext_ln1118_2_fu_132_p0() {
    sext_ln1118_2_fu_132_p0 = data_6_V_read.read();
}

void dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config13_s::thread_sext_ln1118_2_fu_132_p1() {
    sext_ln1118_2_fu_132_p1 = esl_sext<32,27>(sext_ln1118_2_fu_132_p0.read());
}

void dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config13_s::thread_sext_ln1118_3_fu_160_p0() {
    sext_ln1118_3_fu_160_p0 = data_7_V_read.read();
}

void dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config13_s::thread_sext_ln1118_3_fu_160_p1() {
    sext_ln1118_3_fu_160_p1 = esl_sext<32,27>(sext_ln1118_3_fu_160_p0.read());
}

void dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config13_s::thread_sext_ln1118_4_fu_188_p0() {
    sext_ln1118_4_fu_188_p0 = data_8_V_read.read();
}

void dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config13_s::thread_sext_ln1118_4_fu_188_p1() {
    sext_ln1118_4_fu_188_p1 = esl_sext<32,27>(sext_ln1118_4_fu_188_p0.read());
}

void dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config13_s::thread_sext_ln1118_5_fu_216_p0() {
    sext_ln1118_5_fu_216_p0 = data_9_V_read.read();
}

void dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config13_s::thread_sext_ln1118_5_fu_216_p1() {
    sext_ln1118_5_fu_216_p1 = esl_sext<32,27>(sext_ln1118_5_fu_216_p0.read());
}

void dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config13_s::thread_sext_ln1118_6_fu_244_p0() {
    sext_ln1118_6_fu_244_p0 = data_10_V_read.read();
}

void dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config13_s::thread_sext_ln1118_6_fu_244_p1() {
    sext_ln1118_6_fu_244_p1 = esl_sext<32,27>(sext_ln1118_6_fu_244_p0.read());
}

void dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config13_s::thread_sext_ln1118_fu_76_p0() {
    sext_ln1118_fu_76_p0 = data_2_V_read.read();
}

void dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config13_s::thread_sext_ln1118_fu_76_p1() {
    sext_ln1118_fu_76_p1 = esl_sext<32,27>(sext_ln1118_fu_76_p0.read());
}

void dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config13_s::thread_shl_ln1118_1_fu_136_p1() {
    shl_ln1118_1_fu_136_p1 = data_6_V_read.read();
}

void dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config13_s::thread_shl_ln1118_1_fu_136_p3() {
    shl_ln1118_1_fu_136_p3 = esl_concat<27,5>(shl_ln1118_1_fu_136_p1.read(), ap_const_lv5_0);
}

void dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config13_s::thread_shl_ln1118_2_fu_164_p1() {
    shl_ln1118_2_fu_164_p1 = data_7_V_read.read();
}

void dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config13_s::thread_shl_ln1118_2_fu_164_p3() {
    shl_ln1118_2_fu_164_p3 = esl_concat<27,5>(shl_ln1118_2_fu_164_p1.read(), ap_const_lv5_0);
}

void dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config13_s::thread_shl_ln1118_3_fu_192_p1() {
    shl_ln1118_3_fu_192_p1 = data_8_V_read.read();
}

void dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config13_s::thread_shl_ln1118_3_fu_192_p3() {
    shl_ln1118_3_fu_192_p3 = esl_concat<27,5>(shl_ln1118_3_fu_192_p1.read(), ap_const_lv5_0);
}

void dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config13_s::thread_shl_ln1118_4_fu_220_p1() {
    shl_ln1118_4_fu_220_p1 = data_9_V_read.read();
}

void dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config13_s::thread_shl_ln1118_4_fu_220_p3() {
    shl_ln1118_4_fu_220_p3 = esl_concat<27,5>(shl_ln1118_4_fu_220_p1.read(), ap_const_lv5_0);
}

void dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config13_s::thread_shl_ln1118_5_fu_248_p1() {
    shl_ln1118_5_fu_248_p1 = data_10_V_read.read();
}

void dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config13_s::thread_shl_ln1118_5_fu_248_p3() {
    shl_ln1118_5_fu_248_p3 = esl_concat<27,5>(shl_ln1118_5_fu_248_p1.read(), ap_const_lv5_0);
}

void dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config13_s::thread_shl_ln1118_s_fu_108_p1() {
    shl_ln1118_s_fu_108_p1 = data_4_V_read.read();
}

void dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config13_s::thread_shl_ln1118_s_fu_108_p3() {
    shl_ln1118_s_fu_108_p3 = esl_concat<27,5>(shl_ln1118_s_fu_108_p1.read(), ap_const_lv5_0);
}

void dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config13_s::thread_shl_ln_fu_80_p1() {
    shl_ln_fu_80_p1 = data_2_V_read.read();
}

void dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config13_s::thread_shl_ln_fu_80_p3() {
    shl_ln_fu_80_p3 = esl_concat<27,5>(shl_ln_fu_80_p1.read(), ap_const_lv5_0);
}

void dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config13_s::thread_sub_ln1118_10_fu_362_p2() {
    sub_ln1118_10_fu_362_p2 = (!ap_const_lv32_0.is_01() || !shl_ln1118_2_fu_164_p3.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_0) - sc_biguint<32>(shl_ln1118_2_fu_164_p3.read()));
}

void dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config13_s::thread_sub_ln1118_11_fu_378_p2() {
    sub_ln1118_11_fu_378_p2 = (!ap_const_lv32_0.is_01() || !shl_ln1118_3_fu_192_p3.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_0) - sc_biguint<32>(shl_ln1118_3_fu_192_p3.read()));
}

void dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config13_s::thread_sub_ln1118_12_fu_394_p2() {
    sub_ln1118_12_fu_394_p2 = (!ap_const_lv32_0.is_01() || !shl_ln1118_4_fu_220_p3.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_0) - sc_biguint<32>(shl_ln1118_4_fu_220_p3.read()));
}

void dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config13_s::thread_sub_ln1118_13_fu_410_p2() {
    sub_ln1118_13_fu_410_p2 = (!ap_const_lv32_0.is_01() || !shl_ln1118_5_fu_248_p3.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_0) - sc_biguint<32>(shl_ln1118_5_fu_248_p3.read()));
}

void dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config13_s::thread_sub_ln1118_1_fu_116_p2() {
    sub_ln1118_1_fu_116_p2 = (!shl_ln1118_s_fu_108_p3.read().is_01() || !sext_ln1118_1_fu_104_p1.read().is_01())? sc_lv<32>(): (sc_biguint<32>(shl_ln1118_s_fu_108_p3.read()) - sc_bigint<32>(sext_ln1118_1_fu_104_p1.read()));
}

void dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config13_s::thread_sub_ln1118_2_fu_144_p2() {
    sub_ln1118_2_fu_144_p2 = (!ap_const_lv32_0.is_01() || !shl_ln1118_1_fu_136_p3.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_0) - sc_biguint<32>(shl_ln1118_1_fu_136_p3.read()));
}

void dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config13_s::thread_sub_ln1118_3_fu_172_p2() {
    sub_ln1118_3_fu_172_p2 = (!shl_ln1118_2_fu_164_p3.read().is_01() || !sext_ln1118_3_fu_160_p1.read().is_01())? sc_lv<32>(): (sc_biguint<32>(shl_ln1118_2_fu_164_p3.read()) - sc_bigint<32>(sext_ln1118_3_fu_160_p1.read()));
}

void dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config13_s::thread_sub_ln1118_4_fu_200_p2() {
    sub_ln1118_4_fu_200_p2 = (!shl_ln1118_3_fu_192_p3.read().is_01() || !sext_ln1118_4_fu_188_p1.read().is_01())? sc_lv<32>(): (sc_biguint<32>(shl_ln1118_3_fu_192_p3.read()) - sc_bigint<32>(sext_ln1118_4_fu_188_p1.read()));
}

void dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config13_s::thread_sub_ln1118_5_fu_228_p2() {
    sub_ln1118_5_fu_228_p2 = (!shl_ln1118_4_fu_220_p3.read().is_01() || !sext_ln1118_5_fu_216_p1.read().is_01())? sc_lv<32>(): (sc_biguint<32>(shl_ln1118_4_fu_220_p3.read()) - sc_bigint<32>(sext_ln1118_5_fu_216_p1.read()));
}

void dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config13_s::thread_sub_ln1118_6_fu_256_p2() {
    sub_ln1118_6_fu_256_p2 = (!shl_ln1118_5_fu_248_p3.read().is_01() || !sext_ln1118_6_fu_244_p1.read().is_01())? sc_lv<32>(): (sc_biguint<32>(shl_ln1118_5_fu_248_p3.read()) - sc_bigint<32>(sext_ln1118_6_fu_244_p1.read()));
}

void dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config13_s::thread_sub_ln1118_7_fu_314_p2() {
    sub_ln1118_7_fu_314_p2 = (!shl_ln_fu_80_p3.read().is_01() || !sext_ln1118_fu_76_p1.read().is_01())? sc_lv<32>(): (sc_biguint<32>(shl_ln_fu_80_p3.read()) - sc_bigint<32>(sext_ln1118_fu_76_p1.read()));
}

void dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config13_s::thread_sub_ln1118_8_fu_330_p2() {
    sub_ln1118_8_fu_330_p2 = (!ap_const_lv32_0.is_01() || !shl_ln1118_s_fu_108_p3.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_0) - sc_biguint<32>(shl_ln1118_s_fu_108_p3.read()));
}

void dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config13_s::thread_sub_ln1118_9_fu_346_p2() {
    sub_ln1118_9_fu_346_p2 = (!shl_ln1118_1_fu_136_p3.read().is_01() || !sext_ln1118_2_fu_132_p1.read().is_01())? sc_lv<32>(): (sc_biguint<32>(shl_ln1118_1_fu_136_p3.read()) - sc_bigint<32>(sext_ln1118_2_fu_132_p1.read()));
}

void dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config13_s::thread_sub_ln1118_fu_88_p2() {
    sub_ln1118_fu_88_p2 = (!ap_const_lv32_0.is_01() || !shl_ln_fu_80_p3.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_0) - sc_biguint<32>(shl_ln_fu_80_p3.read()));
}

void dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config13_s::thread_trunc_ln708_10_fu_384_p4() {
    trunc_ln708_10_fu_384_p4 = sub_ln1118_11_fu_378_p2.read().range(31, 5);
}

void dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config13_s::thread_trunc_ln708_11_fu_400_p4() {
    trunc_ln708_11_fu_400_p4 = sub_ln1118_12_fu_394_p2.read().range(31, 5);
}

void dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config13_s::thread_trunc_ln708_12_fu_416_p4() {
    trunc_ln708_12_fu_416_p4 = sub_ln1118_13_fu_410_p2.read().range(31, 5);
}

void dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config13_s::thread_trunc_ln708_1_fu_150_p4() {
    trunc_ln708_1_fu_150_p4 = sub_ln1118_2_fu_144_p2.read().range(31, 5);
}

void dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config13_s::thread_trunc_ln708_2_fu_178_p4() {
    trunc_ln708_2_fu_178_p4 = sub_ln1118_3_fu_172_p2.read().range(31, 5);
}

void dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config13_s::thread_trunc_ln708_3_fu_206_p4() {
    trunc_ln708_3_fu_206_p4 = sub_ln1118_4_fu_200_p2.read().range(31, 5);
}

void dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config13_s::thread_trunc_ln708_4_fu_234_p4() {
    trunc_ln708_4_fu_234_p4 = sub_ln1118_5_fu_228_p2.read().range(31, 5);
}

void dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config13_s::thread_trunc_ln708_5_fu_262_p4() {
    trunc_ln708_5_fu_262_p4 = sub_ln1118_6_fu_256_p2.read().range(31, 5);
}

void dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config13_s::thread_trunc_ln708_6_fu_320_p4() {
    trunc_ln708_6_fu_320_p4 = sub_ln1118_7_fu_314_p2.read().range(31, 5);
}

void dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config13_s::thread_trunc_ln708_7_fu_336_p4() {
    trunc_ln708_7_fu_336_p4 = sub_ln1118_8_fu_330_p2.read().range(31, 5);
}

void dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config13_s::thread_trunc_ln708_8_fu_352_p4() {
    trunc_ln708_8_fu_352_p4 = sub_ln1118_9_fu_346_p2.read().range(31, 5);
}

void dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config13_s::thread_trunc_ln708_9_fu_368_p4() {
    trunc_ln708_9_fu_368_p4 = sub_ln1118_10_fu_362_p2.read().range(31, 5);
}

void dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config13_s::thread_trunc_ln708_s_fu_122_p4() {
    trunc_ln708_s_fu_122_p4 = sub_ln1118_1_fu_116_p2.read().range(31, 5);
}

void dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config13_s::thread_trunc_ln_fu_94_p4() {
    trunc_ln_fu_94_p4 = sub_ln1118_fu_88_p2.read().range(31, 5);
}

}

