// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config13_s_HH_
#define _dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config13_s_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config13_s : public sc_module {
    // Port declarations 10
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<27> > data_2_V_read;
    sc_in< sc_lv<27> > data_4_V_read;
    sc_in< sc_lv<27> > data_6_V_read;
    sc_in< sc_lv<27> > data_7_V_read;
    sc_in< sc_lv<27> > data_8_V_read;
    sc_in< sc_lv<27> > data_9_V_read;
    sc_in< sc_lv<27> > data_10_V_read;
    sc_out< sc_lv<27> > ap_return_0;
    sc_out< sc_lv<27> > ap_return_1;


    // Module declarations
    dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config13_s(sc_module_name name);
    SC_HAS_PROCESS(dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config13_s);

    ~dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config13_s();

    sc_trace_file* mVcdFile;

    sc_signal< sc_lv<27> > sext_ln1118_fu_76_p0;
    sc_signal< sc_lv<27> > shl_ln_fu_80_p1;
    sc_signal< sc_lv<32> > shl_ln_fu_80_p3;
    sc_signal< sc_lv<32> > sub_ln1118_fu_88_p2;
    sc_signal< sc_lv<27> > sext_ln1118_1_fu_104_p0;
    sc_signal< sc_lv<27> > shl_ln1118_s_fu_108_p1;
    sc_signal< sc_lv<32> > shl_ln1118_s_fu_108_p3;
    sc_signal< sc_lv<32> > sext_ln1118_1_fu_104_p1;
    sc_signal< sc_lv<32> > sub_ln1118_1_fu_116_p2;
    sc_signal< sc_lv<27> > sext_ln1118_2_fu_132_p0;
    sc_signal< sc_lv<27> > shl_ln1118_1_fu_136_p1;
    sc_signal< sc_lv<32> > shl_ln1118_1_fu_136_p3;
    sc_signal< sc_lv<32> > sub_ln1118_2_fu_144_p2;
    sc_signal< sc_lv<27> > sext_ln1118_3_fu_160_p0;
    sc_signal< sc_lv<27> > shl_ln1118_2_fu_164_p1;
    sc_signal< sc_lv<32> > shl_ln1118_2_fu_164_p3;
    sc_signal< sc_lv<32> > sext_ln1118_3_fu_160_p1;
    sc_signal< sc_lv<32> > sub_ln1118_3_fu_172_p2;
    sc_signal< sc_lv<27> > sext_ln1118_4_fu_188_p0;
    sc_signal< sc_lv<27> > shl_ln1118_3_fu_192_p1;
    sc_signal< sc_lv<32> > shl_ln1118_3_fu_192_p3;
    sc_signal< sc_lv<32> > sext_ln1118_4_fu_188_p1;
    sc_signal< sc_lv<32> > sub_ln1118_4_fu_200_p2;
    sc_signal< sc_lv<27> > sext_ln1118_5_fu_216_p0;
    sc_signal< sc_lv<27> > shl_ln1118_4_fu_220_p1;
    sc_signal< sc_lv<32> > shl_ln1118_4_fu_220_p3;
    sc_signal< sc_lv<32> > sext_ln1118_5_fu_216_p1;
    sc_signal< sc_lv<32> > sub_ln1118_5_fu_228_p2;
    sc_signal< sc_lv<27> > sext_ln1118_6_fu_244_p0;
    sc_signal< sc_lv<27> > shl_ln1118_5_fu_248_p1;
    sc_signal< sc_lv<32> > shl_ln1118_5_fu_248_p3;
    sc_signal< sc_lv<32> > sext_ln1118_6_fu_244_p1;
    sc_signal< sc_lv<32> > sub_ln1118_6_fu_256_p2;
    sc_signal< sc_lv<27> > trunc_ln708_s_fu_122_p4;
    sc_signal< sc_lv<27> > trunc_ln_fu_94_p4;
    sc_signal< sc_lv<27> > trunc_ln708_2_fu_178_p4;
    sc_signal< sc_lv<27> > trunc_ln708_1_fu_150_p4;
    sc_signal< sc_lv<27> > add_ln703_fu_272_p2;
    sc_signal< sc_lv<27> > add_ln703_1_fu_278_p2;
    sc_signal< sc_lv<27> > trunc_ln708_4_fu_234_p4;
    sc_signal< sc_lv<27> > trunc_ln708_3_fu_206_p4;
    sc_signal< sc_lv<27> > trunc_ln708_5_fu_262_p4;
    sc_signal< sc_lv<27> > add_ln703_3_fu_290_p2;
    sc_signal< sc_lv<27> > add_ln703_4_fu_296_p2;
    sc_signal< sc_lv<27> > add_ln703_2_fu_284_p2;
    sc_signal< sc_lv<27> > add_ln703_5_fu_302_p2;
    sc_signal< sc_lv<32> > sext_ln1118_fu_76_p1;
    sc_signal< sc_lv<32> > sub_ln1118_7_fu_314_p2;
    sc_signal< sc_lv<32> > sub_ln1118_8_fu_330_p2;
    sc_signal< sc_lv<32> > sext_ln1118_2_fu_132_p1;
    sc_signal< sc_lv<32> > sub_ln1118_9_fu_346_p2;
    sc_signal< sc_lv<32> > sub_ln1118_10_fu_362_p2;
    sc_signal< sc_lv<32> > sub_ln1118_11_fu_378_p2;
    sc_signal< sc_lv<32> > sub_ln1118_12_fu_394_p2;
    sc_signal< sc_lv<32> > sub_ln1118_13_fu_410_p2;
    sc_signal< sc_lv<27> > trunc_ln708_7_fu_336_p4;
    sc_signal< sc_lv<27> > trunc_ln708_6_fu_320_p4;
    sc_signal< sc_lv<27> > trunc_ln708_9_fu_368_p4;
    sc_signal< sc_lv<27> > trunc_ln708_8_fu_352_p4;
    sc_signal< sc_lv<27> > add_ln703_7_fu_426_p2;
    sc_signal< sc_lv<27> > add_ln703_8_fu_432_p2;
    sc_signal< sc_lv<27> > trunc_ln708_11_fu_400_p4;
    sc_signal< sc_lv<27> > trunc_ln708_10_fu_384_p4;
    sc_signal< sc_lv<27> > trunc_ln708_12_fu_416_p4;
    sc_signal< sc_lv<27> > add_ln703_10_fu_444_p2;
    sc_signal< sc_lv<27> > add_ln703_11_fu_450_p2;
    sc_signal< sc_lv<27> > add_ln703_9_fu_438_p2;
    sc_signal< sc_lv<27> > add_ln703_12_fu_456_p2;
    sc_signal< sc_lv<27> > add_ln703_6_fu_308_p2;
    sc_signal< sc_lv<27> > acc_1_V_fu_462_p2;
    static const sc_logic ap_const_logic_1;
    static const bool ap_const_boolean_1;
    static const sc_lv<5> ap_const_lv5_0;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<32> ap_const_lv32_1F;
    static const sc_lv<27> ap_const_lv27_A000;
    static const sc_lv<27> ap_const_lv27_7FF6000;
    static const sc_logic ap_const_logic_0;
    // Thread declarations
    void thread_acc_1_V_fu_462_p2();
    void thread_add_ln703_10_fu_444_p2();
    void thread_add_ln703_11_fu_450_p2();
    void thread_add_ln703_12_fu_456_p2();
    void thread_add_ln703_1_fu_278_p2();
    void thread_add_ln703_2_fu_284_p2();
    void thread_add_ln703_3_fu_290_p2();
    void thread_add_ln703_4_fu_296_p2();
    void thread_add_ln703_5_fu_302_p2();
    void thread_add_ln703_6_fu_308_p2();
    void thread_add_ln703_7_fu_426_p2();
    void thread_add_ln703_8_fu_432_p2();
    void thread_add_ln703_9_fu_438_p2();
    void thread_add_ln703_fu_272_p2();
    void thread_ap_ready();
    void thread_ap_return_0();
    void thread_ap_return_1();
    void thread_sext_ln1118_1_fu_104_p0();
    void thread_sext_ln1118_1_fu_104_p1();
    void thread_sext_ln1118_2_fu_132_p0();
    void thread_sext_ln1118_2_fu_132_p1();
    void thread_sext_ln1118_3_fu_160_p0();
    void thread_sext_ln1118_3_fu_160_p1();
    void thread_sext_ln1118_4_fu_188_p0();
    void thread_sext_ln1118_4_fu_188_p1();
    void thread_sext_ln1118_5_fu_216_p0();
    void thread_sext_ln1118_5_fu_216_p1();
    void thread_sext_ln1118_6_fu_244_p0();
    void thread_sext_ln1118_6_fu_244_p1();
    void thread_sext_ln1118_fu_76_p0();
    void thread_sext_ln1118_fu_76_p1();
    void thread_shl_ln1118_1_fu_136_p1();
    void thread_shl_ln1118_1_fu_136_p3();
    void thread_shl_ln1118_2_fu_164_p1();
    void thread_shl_ln1118_2_fu_164_p3();
    void thread_shl_ln1118_3_fu_192_p1();
    void thread_shl_ln1118_3_fu_192_p3();
    void thread_shl_ln1118_4_fu_220_p1();
    void thread_shl_ln1118_4_fu_220_p3();
    void thread_shl_ln1118_5_fu_248_p1();
    void thread_shl_ln1118_5_fu_248_p3();
    void thread_shl_ln1118_s_fu_108_p1();
    void thread_shl_ln1118_s_fu_108_p3();
    void thread_shl_ln_fu_80_p1();
    void thread_shl_ln_fu_80_p3();
    void thread_sub_ln1118_10_fu_362_p2();
    void thread_sub_ln1118_11_fu_378_p2();
    void thread_sub_ln1118_12_fu_394_p2();
    void thread_sub_ln1118_13_fu_410_p2();
    void thread_sub_ln1118_1_fu_116_p2();
    void thread_sub_ln1118_2_fu_144_p2();
    void thread_sub_ln1118_3_fu_172_p2();
    void thread_sub_ln1118_4_fu_200_p2();
    void thread_sub_ln1118_5_fu_228_p2();
    void thread_sub_ln1118_6_fu_256_p2();
    void thread_sub_ln1118_7_fu_314_p2();
    void thread_sub_ln1118_8_fu_330_p2();
    void thread_sub_ln1118_9_fu_346_p2();
    void thread_sub_ln1118_fu_88_p2();
    void thread_trunc_ln708_10_fu_384_p4();
    void thread_trunc_ln708_11_fu_400_p4();
    void thread_trunc_ln708_12_fu_416_p4();
    void thread_trunc_ln708_1_fu_150_p4();
    void thread_trunc_ln708_2_fu_178_p4();
    void thread_trunc_ln708_3_fu_206_p4();
    void thread_trunc_ln708_4_fu_234_p4();
    void thread_trunc_ln708_5_fu_262_p4();
    void thread_trunc_ln708_6_fu_320_p4();
    void thread_trunc_ln708_7_fu_336_p4();
    void thread_trunc_ln708_8_fu_352_p4();
    void thread_trunc_ln708_9_fu_368_p4();
    void thread_trunc_ln708_s_fu_122_p4();
    void thread_trunc_ln_fu_94_p4();
};

}

using namespace ap_rtl;

#endif
