-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2020.1
-- Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity dense_array_array_ap_fixed_27_9_5_3_0_12u_config11_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    data_stream_V_data_0_V_dout : IN STD_LOGIC_VECTOR (26 downto 0);
    data_stream_V_data_0_V_empty_n : IN STD_LOGIC;
    data_stream_V_data_0_V_read : OUT STD_LOGIC;
    data_stream_V_data_1_V_dout : IN STD_LOGIC_VECTOR (26 downto 0);
    data_stream_V_data_1_V_empty_n : IN STD_LOGIC;
    data_stream_V_data_1_V_read : OUT STD_LOGIC;
    data_stream_V_data_2_V_dout : IN STD_LOGIC_VECTOR (26 downto 0);
    data_stream_V_data_2_V_empty_n : IN STD_LOGIC;
    data_stream_V_data_2_V_read : OUT STD_LOGIC;
    data_stream_V_data_3_V_dout : IN STD_LOGIC_VECTOR (26 downto 0);
    data_stream_V_data_3_V_empty_n : IN STD_LOGIC;
    data_stream_V_data_3_V_read : OUT STD_LOGIC;
    data_stream_V_data_4_V_dout : IN STD_LOGIC_VECTOR (26 downto 0);
    data_stream_V_data_4_V_empty_n : IN STD_LOGIC;
    data_stream_V_data_4_V_read : OUT STD_LOGIC;
    data_stream_V_data_5_V_dout : IN STD_LOGIC_VECTOR (26 downto 0);
    data_stream_V_data_5_V_empty_n : IN STD_LOGIC;
    data_stream_V_data_5_V_read : OUT STD_LOGIC;
    data_stream_V_data_6_V_dout : IN STD_LOGIC_VECTOR (26 downto 0);
    data_stream_V_data_6_V_empty_n : IN STD_LOGIC;
    data_stream_V_data_6_V_read : OUT STD_LOGIC;
    data_stream_V_data_7_V_dout : IN STD_LOGIC_VECTOR (26 downto 0);
    data_stream_V_data_7_V_empty_n : IN STD_LOGIC;
    data_stream_V_data_7_V_read : OUT STD_LOGIC;
    data_stream_V_data_8_V_dout : IN STD_LOGIC_VECTOR (26 downto 0);
    data_stream_V_data_8_V_empty_n : IN STD_LOGIC;
    data_stream_V_data_8_V_read : OUT STD_LOGIC;
    data_stream_V_data_9_V_dout : IN STD_LOGIC_VECTOR (26 downto 0);
    data_stream_V_data_9_V_empty_n : IN STD_LOGIC;
    data_stream_V_data_9_V_read : OUT STD_LOGIC;
    data_stream_V_data_10_V_dout : IN STD_LOGIC_VECTOR (26 downto 0);
    data_stream_V_data_10_V_empty_n : IN STD_LOGIC;
    data_stream_V_data_10_V_read : OUT STD_LOGIC;
    data_stream_V_data_11_V_dout : IN STD_LOGIC_VECTOR (26 downto 0);
    data_stream_V_data_11_V_empty_n : IN STD_LOGIC;
    data_stream_V_data_11_V_read : OUT STD_LOGIC;
    data_stream_V_data_12_V_dout : IN STD_LOGIC_VECTOR (26 downto 0);
    data_stream_V_data_12_V_empty_n : IN STD_LOGIC;
    data_stream_V_data_12_V_read : OUT STD_LOGIC;
    data_stream_V_data_13_V_dout : IN STD_LOGIC_VECTOR (26 downto 0);
    data_stream_V_data_13_V_empty_n : IN STD_LOGIC;
    data_stream_V_data_13_V_read : OUT STD_LOGIC;
    data_stream_V_data_14_V_dout : IN STD_LOGIC_VECTOR (26 downto 0);
    data_stream_V_data_14_V_empty_n : IN STD_LOGIC;
    data_stream_V_data_14_V_read : OUT STD_LOGIC;
    data_stream_V_data_15_V_dout : IN STD_LOGIC_VECTOR (26 downto 0);
    data_stream_V_data_15_V_empty_n : IN STD_LOGIC;
    data_stream_V_data_15_V_read : OUT STD_LOGIC;
    res_stream_V_data_0_V_din : OUT STD_LOGIC_VECTOR (26 downto 0);
    res_stream_V_data_0_V_full_n : IN STD_LOGIC;
    res_stream_V_data_0_V_write : OUT STD_LOGIC;
    res_stream_V_data_1_V_din : OUT STD_LOGIC_VECTOR (26 downto 0);
    res_stream_V_data_1_V_full_n : IN STD_LOGIC;
    res_stream_V_data_1_V_write : OUT STD_LOGIC;
    res_stream_V_data_2_V_din : OUT STD_LOGIC_VECTOR (26 downto 0);
    res_stream_V_data_2_V_full_n : IN STD_LOGIC;
    res_stream_V_data_2_V_write : OUT STD_LOGIC;
    res_stream_V_data_3_V_din : OUT STD_LOGIC_VECTOR (26 downto 0);
    res_stream_V_data_3_V_full_n : IN STD_LOGIC;
    res_stream_V_data_3_V_write : OUT STD_LOGIC;
    res_stream_V_data_4_V_din : OUT STD_LOGIC_VECTOR (26 downto 0);
    res_stream_V_data_4_V_full_n : IN STD_LOGIC;
    res_stream_V_data_4_V_write : OUT STD_LOGIC;
    res_stream_V_data_5_V_din : OUT STD_LOGIC_VECTOR (26 downto 0);
    res_stream_V_data_5_V_full_n : IN STD_LOGIC;
    res_stream_V_data_5_V_write : OUT STD_LOGIC;
    res_stream_V_data_6_V_din : OUT STD_LOGIC_VECTOR (26 downto 0);
    res_stream_V_data_6_V_full_n : IN STD_LOGIC;
    res_stream_V_data_6_V_write : OUT STD_LOGIC;
    res_stream_V_data_7_V_din : OUT STD_LOGIC_VECTOR (26 downto 0);
    res_stream_V_data_7_V_full_n : IN STD_LOGIC;
    res_stream_V_data_7_V_write : OUT STD_LOGIC;
    res_stream_V_data_8_V_din : OUT STD_LOGIC_VECTOR (26 downto 0);
    res_stream_V_data_8_V_full_n : IN STD_LOGIC;
    res_stream_V_data_8_V_write : OUT STD_LOGIC;
    res_stream_V_data_9_V_din : OUT STD_LOGIC_VECTOR (26 downto 0);
    res_stream_V_data_9_V_full_n : IN STD_LOGIC;
    res_stream_V_data_9_V_write : OUT STD_LOGIC;
    res_stream_V_data_10_V_din : OUT STD_LOGIC_VECTOR (26 downto 0);
    res_stream_V_data_10_V_full_n : IN STD_LOGIC;
    res_stream_V_data_10_V_write : OUT STD_LOGIC;
    res_stream_V_data_11_V_din : OUT STD_LOGIC_VECTOR (26 downto 0);
    res_stream_V_data_11_V_full_n : IN STD_LOGIC;
    res_stream_V_data_11_V_write : OUT STD_LOGIC );
end;


architecture behav of dense_array_array_ap_fixed_27_9_5_3_0_12u_config11_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv4_6 : STD_LOGIC_VECTOR (3 downto 0) := "0110";
    constant ap_const_lv4_5 : STD_LOGIC_VECTOR (3 downto 0) := "0101";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv4_4 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_const_lv4_3 : STD_LOGIC_VECTOR (3 downto 0) := "0011";
    constant ap_const_lv4_2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv4_C : STD_LOGIC_VECTOR (3 downto 0) := "1100";
    constant ap_const_lv4_B : STD_LOGIC_VECTOR (3 downto 0) := "1011";
    constant ap_const_lv4_A : STD_LOGIC_VECTOR (3 downto 0) := "1010";
    constant ap_const_lv4_7 : STD_LOGIC_VECTOR (3 downto 0) := "0111";
    constant ap_const_lv4_9 : STD_LOGIC_VECTOR (3 downto 0) := "1001";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv4_D : STD_LOGIC_VECTOR (3 downto 0) := "1101";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv4_E : STD_LOGIC_VECTOR (3 downto 0) := "1110";
    constant ap_const_lv27_0 : STD_LOGIC_VECTOR (26 downto 0) := "000000000000000000000000000";
    constant ap_const_lv5_10 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";

    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal data_stream_V_data_0_V_blk_n : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal data_stream_V_data_1_V_blk_n : STD_LOGIC;
    signal data_stream_V_data_2_V_blk_n : STD_LOGIC;
    signal data_stream_V_data_3_V_blk_n : STD_LOGIC;
    signal data_stream_V_data_4_V_blk_n : STD_LOGIC;
    signal data_stream_V_data_5_V_blk_n : STD_LOGIC;
    signal data_stream_V_data_6_V_blk_n : STD_LOGIC;
    signal data_stream_V_data_7_V_blk_n : STD_LOGIC;
    signal data_stream_V_data_8_V_blk_n : STD_LOGIC;
    signal data_stream_V_data_9_V_blk_n : STD_LOGIC;
    signal data_stream_V_data_10_V_blk_n : STD_LOGIC;
    signal data_stream_V_data_11_V_blk_n : STD_LOGIC;
    signal data_stream_V_data_12_V_blk_n : STD_LOGIC;
    signal data_stream_V_data_13_V_blk_n : STD_LOGIC;
    signal data_stream_V_data_14_V_blk_n : STD_LOGIC;
    signal data_stream_V_data_15_V_blk_n : STD_LOGIC;
    signal res_stream_V_data_0_V_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal res_stream_V_data_1_V_blk_n : STD_LOGIC;
    signal res_stream_V_data_2_V_blk_n : STD_LOGIC;
    signal res_stream_V_data_3_V_blk_n : STD_LOGIC;
    signal res_stream_V_data_4_V_blk_n : STD_LOGIC;
    signal res_stream_V_data_5_V_blk_n : STD_LOGIC;
    signal res_stream_V_data_6_V_blk_n : STD_LOGIC;
    signal res_stream_V_data_7_V_blk_n : STD_LOGIC;
    signal res_stream_V_data_8_V_blk_n : STD_LOGIC;
    signal res_stream_V_data_9_V_blk_n : STD_LOGIC;
    signal res_stream_V_data_10_V_blk_n : STD_LOGIC;
    signal res_stream_V_data_11_V_blk_n : STD_LOGIC;
    signal i_in_0_reg_465 : STD_LOGIC_VECTOR (4 downto 0);
    signal icmp_ln41_fu_542_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state2_pp0_stage0_iter0 : BOOLEAN;
    signal io_acc_block_signal_op170 : STD_LOGIC;
    signal ap_block_state3_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal i_in_fu_548_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal trunc_ln203_fu_554_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln203_reg_1552 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal ap_block_state1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_pp0_exit_iter0_state2 : STD_LOGIC;
    signal grp_dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config11_s_fu_476_ap_start : STD_LOGIC;
    signal grp_dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config11_s_fu_476_ap_done : STD_LOGIC;
    signal grp_dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config11_s_fu_476_ap_idle : STD_LOGIC;
    signal grp_dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config11_s_fu_476_ap_ready : STD_LOGIC;
    signal grp_dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config11_s_fu_476_ap_return_0 : STD_LOGIC_VECTOR (26 downto 0);
    signal grp_dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config11_s_fu_476_ap_return_1 : STD_LOGIC_VECTOR (26 downto 0);
    signal grp_dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config11_s_fu_476_ap_return_2 : STD_LOGIC_VECTOR (26 downto 0);
    signal grp_dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config11_s_fu_476_ap_return_3 : STD_LOGIC_VECTOR (26 downto 0);
    signal grp_dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config11_s_fu_476_ap_return_4 : STD_LOGIC_VECTOR (26 downto 0);
    signal grp_dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config11_s_fu_476_ap_return_5 : STD_LOGIC_VECTOR (26 downto 0);
    signal grp_dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config11_s_fu_476_ap_return_6 : STD_LOGIC_VECTOR (26 downto 0);
    signal grp_dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config11_s_fu_476_ap_start_reg : STD_LOGIC := '0';
    signal data_243_V_fu_136 : STD_LOGIC_VECTOR (26 downto 0);
    signal data_250_V_fu_140 : STD_LOGIC_VECTOR (26 downto 0);
    signal data_243_V_1_fu_144 : STD_LOGIC_VECTOR (26 downto 0);
    signal data_249_V_fu_148 : STD_LOGIC_VECTOR (26 downto 0);
    signal data_247_V_fu_152 : STD_LOGIC_VECTOR (26 downto 0);
    signal data_243_V_2_fu_156 : STD_LOGIC_VECTOR (26 downto 0);
    signal data_247_V_1_fu_160 : STD_LOGIC_VECTOR (26 downto 0);
    signal data_250_V_1_fu_164 : STD_LOGIC_VECTOR (26 downto 0);
    signal data_249_V_1_fu_168 : STD_LOGIC_VECTOR (26 downto 0);
    signal data_250_V_2_fu_172 : STD_LOGIC_VECTOR (26 downto 0);
    signal data_249_V_2_fu_176 : STD_LOGIC_VECTOR (26 downto 0);
    signal data_247_V_2_fu_180 : STD_LOGIC_VECTOR (26 downto 0);
    signal data_243_V_3_fu_184 : STD_LOGIC_VECTOR (26 downto 0);
    signal data_250_V_3_fu_188 : STD_LOGIC_VECTOR (26 downto 0);
    signal data_249_V_3_fu_192 : STD_LOGIC_VECTOR (26 downto 0);
    signal data_247_V_3_fu_196 : STD_LOGIC_VECTOR (26 downto 0);
    signal data_243_V_4_fu_200 : STD_LOGIC_VECTOR (26 downto 0);
    signal data_250_V_4_fu_204 : STD_LOGIC_VECTOR (26 downto 0);
    signal data_249_V_4_fu_208 : STD_LOGIC_VECTOR (26 downto 0);
    signal data_247_V_4_fu_212 : STD_LOGIC_VECTOR (26 downto 0);
    signal data_250_V_5_fu_216 : STD_LOGIC_VECTOR (26 downto 0);
    signal data_247_V_5_fu_220 : STD_LOGIC_VECTOR (26 downto 0);
    signal data_249_V_5_fu_224 : STD_LOGIC_VECTOR (26 downto 0);
    signal data_247_V_6_fu_228 : STD_LOGIC_VECTOR (26 downto 0);
    signal data_243_V_5_fu_232 : STD_LOGIC_VECTOR (26 downto 0);
    signal data_247_V_7_fu_236 : STD_LOGIC_VECTOR (26 downto 0);
    signal data_249_V_6_fu_240 : STD_LOGIC_VECTOR (26 downto 0);
    signal data_250_V_6_fu_244 : STD_LOGIC_VECTOR (26 downto 0);
    signal data_249_V_7_fu_248 : STD_LOGIC_VECTOR (26 downto 0);
    signal data_247_V_8_fu_252 : STD_LOGIC_VECTOR (26 downto 0);
    signal data_250_V_7_fu_256 : STD_LOGIC_VECTOR (26 downto 0);
    signal data_249_V_8_fu_260 : STD_LOGIC_VECTOR (26 downto 0);
    signal data_247_V_9_fu_264 : STD_LOGIC_VECTOR (26 downto 0);
    signal data_243_V_6_fu_268 : STD_LOGIC_VECTOR (26 downto 0);
    signal data_243_V_7_fu_272 : STD_LOGIC_VECTOR (26 downto 0);
    signal data_250_V_8_fu_276 : STD_LOGIC_VECTOR (26 downto 0);
    signal data_249_V_9_fu_280 : STD_LOGIC_VECTOR (26 downto 0);
    signal data_247_V_10_fu_284 : STD_LOGIC_VECTOR (26 downto 0);
    signal data_247_V_11_fu_288 : STD_LOGIC_VECTOR (26 downto 0);
    signal data_243_V_8_fu_292 : STD_LOGIC_VECTOR (26 downto 0);
    signal data_249_V_10_fu_296 : STD_LOGIC_VECTOR (26 downto 0);
    signal data_250_V_9_fu_300 : STD_LOGIC_VECTOR (26 downto 0);
    signal data_249_V_11_fu_304 : STD_LOGIC_VECTOR (26 downto 0);
    signal data_247_V_12_fu_308 : STD_LOGIC_VECTOR (26 downto 0);
    signal data_243_V_9_fu_312 : STD_LOGIC_VECTOR (26 downto 0);
    signal data_243_V_10_fu_316 : STD_LOGIC_VECTOR (26 downto 0);
    signal data_247_V_13_fu_320 : STD_LOGIC_VECTOR (26 downto 0);
    signal data_249_V_12_fu_324 : STD_LOGIC_VECTOR (26 downto 0);
    signal data_247_V_14_fu_328 : STD_LOGIC_VECTOR (26 downto 0);
    signal data_243_V_11_fu_332 : STD_LOGIC_VECTOR (26 downto 0);
    signal data_247_V_15_fu_336 : STD_LOGIC_VECTOR (26 downto 0);
    signal data_243_V_12_fu_340 : STD_LOGIC_VECTOR (26 downto 0);
    signal data_240_V_fu_344 : STD_LOGIC_VECTOR (26 downto 0);
    signal data_240_V_1_fu_348 : STD_LOGIC_VECTOR (26 downto 0);
    signal data_240_V_2_fu_352 : STD_LOGIC_VECTOR (26 downto 0);
    signal data_240_V_3_fu_356 : STD_LOGIC_VECTOR (26 downto 0);
    signal data_240_V_4_fu_360 : STD_LOGIC_VECTOR (26 downto 0);
    signal data_240_V_5_fu_364 : STD_LOGIC_VECTOR (26 downto 0);
    signal data_240_V_6_fu_368 : STD_LOGIC_VECTOR (26 downto 0);
    signal data_240_V_7_fu_372 : STD_LOGIC_VECTOR (26 downto 0);
    signal data_240_V_8_fu_376 : STD_LOGIC_VECTOR (26 downto 0);
    signal data_240_V_9_fu_380 : STD_LOGIC_VECTOR (26 downto 0);
    signal io_acc_block_signal_op315 : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;

    component dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config11_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        data_3_V_read : IN STD_LOGIC_VECTOR (26 downto 0);
        data_7_V_read : IN STD_LOGIC_VECTOR (26 downto 0);
        data_9_V_read : IN STD_LOGIC_VECTOR (26 downto 0);
        data_10_V_read : IN STD_LOGIC_VECTOR (26 downto 0);
        data_23_V_read : IN STD_LOGIC_VECTOR (26 downto 0);
        data_25_V_read : IN STD_LOGIC_VECTOR (26 downto 0);
        data_26_V_read : IN STD_LOGIC_VECTOR (26 downto 0);
        data_39_V_read : IN STD_LOGIC_VECTOR (26 downto 0);
        data_41_V_read : IN STD_LOGIC_VECTOR (26 downto 0);
        data_42_V_read : IN STD_LOGIC_VECTOR (26 downto 0);
        data_51_V_read : IN STD_LOGIC_VECTOR (26 downto 0);
        data_55_V_read : IN STD_LOGIC_VECTOR (26 downto 0);
        data_57_V_read : IN STD_LOGIC_VECTOR (26 downto 0);
        data_58_V_read : IN STD_LOGIC_VECTOR (26 downto 0);
        data_64_V_read : IN STD_LOGIC_VECTOR (26 downto 0);
        data_67_V_read : IN STD_LOGIC_VECTOR (26 downto 0);
        data_71_V_read : IN STD_LOGIC_VECTOR (26 downto 0);
        data_73_V_read : IN STD_LOGIC_VECTOR (26 downto 0);
        data_74_V_read : IN STD_LOGIC_VECTOR (26 downto 0);
        data_83_V_read : IN STD_LOGIC_VECTOR (26 downto 0);
        data_87_V_read : IN STD_LOGIC_VECTOR (26 downto 0);
        data_89_V_read : IN STD_LOGIC_VECTOR (26 downto 0);
        data_90_V_read : IN STD_LOGIC_VECTOR (26 downto 0);
        data_96_V_read : IN STD_LOGIC_VECTOR (26 downto 0);
        data_99_V_read : IN STD_LOGIC_VECTOR (26 downto 0);
        data_103_V_read : IN STD_LOGIC_VECTOR (26 downto 0);
        data_105_V_read : IN STD_LOGIC_VECTOR (26 downto 0);
        data_112_V_read : IN STD_LOGIC_VECTOR (26 downto 0);
        data_115_V_read : IN STD_LOGIC_VECTOR (26 downto 0);
        data_119_V_read : IN STD_LOGIC_VECTOR (26 downto 0);
        data_121_V_read : IN STD_LOGIC_VECTOR (26 downto 0);
        data_128_V_read : IN STD_LOGIC_VECTOR (26 downto 0);
        data_131_V_read : IN STD_LOGIC_VECTOR (26 downto 0);
        data_135_V_read : IN STD_LOGIC_VECTOR (26 downto 0);
        data_137_V_read : IN STD_LOGIC_VECTOR (26 downto 0);
        data_138_V_read : IN STD_LOGIC_VECTOR (26 downto 0);
        data_144_V_read : IN STD_LOGIC_VECTOR (26 downto 0);
        data_147_V_read : IN STD_LOGIC_VECTOR (26 downto 0);
        data_151_V_read : IN STD_LOGIC_VECTOR (26 downto 0);
        data_153_V_read : IN STD_LOGIC_VECTOR (26 downto 0);
        data_154_V_read : IN STD_LOGIC_VECTOR (26 downto 0);
        data_160_V_read : IN STD_LOGIC_VECTOR (26 downto 0);
        data_163_V_read : IN STD_LOGIC_VECTOR (26 downto 0);
        data_167_V_read : IN STD_LOGIC_VECTOR (26 downto 0);
        data_169_V_read : IN STD_LOGIC_VECTOR (26 downto 0);
        data_170_V_read : IN STD_LOGIC_VECTOR (26 downto 0);
        data_183_V_read : IN STD_LOGIC_VECTOR (26 downto 0);
        data_185_V_read : IN STD_LOGIC_VECTOR (26 downto 0);
        data_186_V_read : IN STD_LOGIC_VECTOR (26 downto 0);
        data_192_V_read : IN STD_LOGIC_VECTOR (26 downto 0);
        data_195_V_read : IN STD_LOGIC_VECTOR (26 downto 0);
        data_199_V_read : IN STD_LOGIC_VECTOR (26 downto 0);
        data_208_V_read : IN STD_LOGIC_VECTOR (26 downto 0);
        data_211_V_read : IN STD_LOGIC_VECTOR (26 downto 0);
        data_215_V_read : IN STD_LOGIC_VECTOR (26 downto 0);
        data_224_V_read : IN STD_LOGIC_VECTOR (26 downto 0);
        data_227_V_read : IN STD_LOGIC_VECTOR (26 downto 0);
        data_231_V_read : IN STD_LOGIC_VECTOR (26 downto 0);
        data_240_V_read : IN STD_LOGIC_VECTOR (26 downto 0);
        data_243_V_read : IN STD_LOGIC_VECTOR (26 downto 0);
        data_247_V_read : IN STD_LOGIC_VECTOR (26 downto 0);
        data_249_V_read : IN STD_LOGIC_VECTOR (26 downto 0);
        ap_return_0 : OUT STD_LOGIC_VECTOR (26 downto 0);
        ap_return_1 : OUT STD_LOGIC_VECTOR (26 downto 0);
        ap_return_2 : OUT STD_LOGIC_VECTOR (26 downto 0);
        ap_return_3 : OUT STD_LOGIC_VECTOR (26 downto 0);
        ap_return_4 : OUT STD_LOGIC_VECTOR (26 downto 0);
        ap_return_5 : OUT STD_LOGIC_VECTOR (26 downto 0);
        ap_return_6 : OUT STD_LOGIC_VECTOR (26 downto 0) );
    end component;



begin
    grp_dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config11_s_fu_476 : component dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config11_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config11_s_fu_476_ap_start,
        ap_done => grp_dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config11_s_fu_476_ap_done,
        ap_idle => grp_dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config11_s_fu_476_ap_idle,
        ap_ready => grp_dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config11_s_fu_476_ap_ready,
        data_3_V_read => data_243_V_1_fu_144,
        data_7_V_read => data_247_V_1_fu_160,
        data_9_V_read => data_249_V_1_fu_168,
        data_10_V_read => data_250_V_2_fu_172,
        data_23_V_read => data_247_V_5_fu_220,
        data_25_V_read => data_249_V_5_fu_224,
        data_26_V_read => data_250_V_5_fu_216,
        data_39_V_read => data_247_V_4_fu_212,
        data_41_V_read => data_249_V_4_fu_208,
        data_42_V_read => data_250_V_4_fu_204,
        data_51_V_read => data_243_V_4_fu_200,
        data_55_V_read => data_247_V_3_fu_196,
        data_57_V_read => data_249_V_3_fu_192,
        data_58_V_read => data_250_V_3_fu_188,
        data_64_V_read => data_240_V_1_fu_348,
        data_67_V_read => data_243_V_3_fu_184,
        data_71_V_read => data_247_V_2_fu_180,
        data_73_V_read => data_249_V_2_fu_176,
        data_74_V_read => data_250_V_1_fu_164,
        data_83_V_read => data_243_V_2_fu_156,
        data_87_V_read => data_247_V_fu_152,
        data_89_V_read => data_249_V_fu_148,
        data_90_V_read => data_250_V_fu_140,
        data_96_V_read => data_240_V_fu_344,
        data_99_V_read => data_243_V_fu_136,
        data_103_V_read => data_247_V_7_fu_236,
        data_105_V_read => data_249_V_6_fu_240,
        data_112_V_read => data_240_V_3_fu_356,
        data_115_V_read => data_243_V_7_fu_272,
        data_119_V_read => data_247_V_11_fu_288,
        data_121_V_read => data_249_V_10_fu_296,
        data_128_V_read => data_240_V_6_fu_368,
        data_131_V_read => data_243_V_9_fu_312,
        data_135_V_read => data_247_V_12_fu_308,
        data_137_V_read => data_249_V_11_fu_304,
        data_138_V_read => data_250_V_9_fu_300,
        data_144_V_read => data_240_V_5_fu_364,
        data_147_V_read => data_243_V_8_fu_292,
        data_151_V_read => data_247_V_10_fu_284,
        data_153_V_read => data_249_V_9_fu_280,
        data_154_V_read => data_250_V_8_fu_276,
        data_160_V_read => data_240_V_4_fu_360,
        data_163_V_read => data_243_V_6_fu_268,
        data_167_V_read => data_247_V_9_fu_264,
        data_169_V_read => data_249_V_8_fu_260,
        data_170_V_read => data_250_V_7_fu_256,
        data_183_V_read => data_247_V_8_fu_252,
        data_185_V_read => data_249_V_7_fu_248,
        data_186_V_read => data_250_V_6_fu_244,
        data_192_V_read => data_240_V_2_fu_352,
        data_195_V_read => data_243_V_5_fu_232,
        data_199_V_read => data_247_V_6_fu_228,
        data_208_V_read => data_240_V_7_fu_372,
        data_211_V_read => data_243_V_10_fu_316,
        data_215_V_read => data_247_V_13_fu_320,
        data_224_V_read => data_240_V_9_fu_380,
        data_227_V_read => data_243_V_12_fu_340,
        data_231_V_read => data_247_V_15_fu_336,
        data_240_V_read => data_240_V_8_fu_376,
        data_243_V_read => data_243_V_11_fu_332,
        data_247_V_read => data_247_V_14_fu_328,
        data_249_V_read => data_249_V_12_fu_324,
        ap_return_0 => grp_dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config11_s_fu_476_ap_return_0,
        ap_return_1 => grp_dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config11_s_fu_476_ap_return_1,
        ap_return_2 => grp_dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config11_s_fu_476_ap_return_2,
        ap_return_3 => grp_dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config11_s_fu_476_ap_return_3,
        ap_return_4 => grp_dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config11_s_fu_476_ap_return_4,
        ap_return_5 => grp_dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config11_s_fu_476_ap_return_5,
        ap_return_6 => grp_dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config11_s_fu_476_ap_return_6);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif ((not(((io_acc_block_signal_op315 = ap_const_logic_0) or (grp_dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config11_s_fu_476_ap_done = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_condition_pp0_exit_iter0_state2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_condition_pp0_exit_iter0_state2))) then 
                    ap_enable_reg_pp0_iter1 <= (ap_const_logic_1 xor ap_condition_pp0_exit_iter0_state2);
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                elsif ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config11_s_fu_476_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config11_s_fu_476_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                    grp_dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config11_s_fu_476_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config11_s_fu_476_ap_ready = ap_const_logic_1)) then 
                    grp_dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config11_s_fu_476_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((internal_ap_ready = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    i_in_0_reg_465_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln41_fu_542_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                i_in_0_reg_465 <= i_in_fu_548_p2;
            elsif ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                i_in_0_reg_465 <= ap_const_lv5_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((trunc_ln203_reg_1552 = ap_const_lv4_4) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                data_240_V_1_fu_348 <= data_stream_V_data_0_V_dout;
                data_243_V_3_fu_184 <= data_stream_V_data_3_V_dout;
                data_247_V_2_fu_180 <= data_stream_V_data_7_V_dout;
                data_249_V_2_fu_176 <= data_stream_V_data_9_V_dout;
                data_250_V_1_fu_164 <= data_stream_V_data_10_V_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((trunc_ln203_reg_1552 = ap_const_lv4_C) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                data_240_V_2_fu_352 <= data_stream_V_data_0_V_dout;
                data_243_V_5_fu_232 <= data_stream_V_data_3_V_dout;
                data_247_V_6_fu_228 <= data_stream_V_data_7_V_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((trunc_ln203_reg_1552 = ap_const_lv4_7) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                data_240_V_3_fu_356 <= data_stream_V_data_0_V_dout;
                data_243_V_7_fu_272 <= data_stream_V_data_3_V_dout;
                data_247_V_11_fu_288 <= data_stream_V_data_7_V_dout;
                data_249_V_10_fu_296 <= data_stream_V_data_9_V_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((trunc_ln203_reg_1552 = ap_const_lv4_A) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                data_240_V_4_fu_360 <= data_stream_V_data_0_V_dout;
                data_243_V_6_fu_268 <= data_stream_V_data_3_V_dout;
                data_247_V_9_fu_264 <= data_stream_V_data_7_V_dout;
                data_249_V_8_fu_260 <= data_stream_V_data_9_V_dout;
                data_250_V_7_fu_256 <= data_stream_V_data_10_V_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((trunc_ln203_reg_1552 = ap_const_lv4_9) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                data_240_V_5_fu_364 <= data_stream_V_data_0_V_dout;
                data_243_V_8_fu_292 <= data_stream_V_data_3_V_dout;
                data_247_V_10_fu_284 <= data_stream_V_data_7_V_dout;
                data_249_V_9_fu_280 <= data_stream_V_data_9_V_dout;
                data_250_V_8_fu_276 <= data_stream_V_data_10_V_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((trunc_ln203_reg_1552 = ap_const_lv4_8) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                data_240_V_6_fu_368 <= data_stream_V_data_0_V_dout;
                data_243_V_9_fu_312 <= data_stream_V_data_3_V_dout;
                data_247_V_12_fu_308 <= data_stream_V_data_7_V_dout;
                data_249_V_11_fu_304 <= data_stream_V_data_9_V_dout;
                data_250_V_9_fu_300 <= data_stream_V_data_10_V_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((trunc_ln203_reg_1552 = ap_const_lv4_D) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                data_240_V_7_fu_372 <= data_stream_V_data_0_V_dout;
                data_243_V_10_fu_316 <= data_stream_V_data_3_V_dout;
                data_247_V_13_fu_320 <= data_stream_V_data_7_V_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((trunc_ln203_reg_1552 = ap_const_lv4_F) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                data_240_V_8_fu_376 <= data_stream_V_data_0_V_dout;
                data_243_V_11_fu_332 <= data_stream_V_data_3_V_dout;
                data_247_V_14_fu_328 <= data_stream_V_data_7_V_dout;
                data_249_V_12_fu_324 <= data_stream_V_data_9_V_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((trunc_ln203_reg_1552 = ap_const_lv4_E) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                data_240_V_9_fu_380 <= data_stream_V_data_0_V_dout;
                data_243_V_12_fu_340 <= data_stream_V_data_3_V_dout;
                data_247_V_15_fu_336 <= data_stream_V_data_7_V_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((trunc_ln203_reg_1552 = ap_const_lv4_6) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                data_240_V_fu_344 <= data_stream_V_data_0_V_dout;
                data_243_V_fu_136 <= data_stream_V_data_3_V_dout;
                data_247_V_7_fu_236 <= data_stream_V_data_7_V_dout;
                data_249_V_6_fu_240 <= data_stream_V_data_9_V_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((trunc_ln203_reg_1552 = ap_const_lv4_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                data_243_V_1_fu_144 <= data_stream_V_data_3_V_dout;
                data_247_V_1_fu_160 <= data_stream_V_data_7_V_dout;
                data_249_V_1_fu_168 <= data_stream_V_data_9_V_dout;
                data_250_V_2_fu_172 <= data_stream_V_data_10_V_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((trunc_ln203_reg_1552 = ap_const_lv4_5) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                data_243_V_2_fu_156 <= data_stream_V_data_3_V_dout;
                data_247_V_fu_152 <= data_stream_V_data_7_V_dout;
                data_249_V_fu_148 <= data_stream_V_data_9_V_dout;
                data_250_V_fu_140 <= data_stream_V_data_10_V_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((trunc_ln203_reg_1552 = ap_const_lv4_3) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                data_243_V_4_fu_200 <= data_stream_V_data_3_V_dout;
                data_247_V_3_fu_196 <= data_stream_V_data_7_V_dout;
                data_249_V_3_fu_192 <= data_stream_V_data_9_V_dout;
                data_250_V_3_fu_188 <= data_stream_V_data_10_V_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((trunc_ln203_reg_1552 = ap_const_lv4_2) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                data_247_V_4_fu_212 <= data_stream_V_data_7_V_dout;
                data_249_V_4_fu_208 <= data_stream_V_data_9_V_dout;
                data_250_V_4_fu_204 <= data_stream_V_data_10_V_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((trunc_ln203_reg_1552 = ap_const_lv4_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                data_247_V_5_fu_220 <= data_stream_V_data_7_V_dout;
                data_249_V_5_fu_224 <= data_stream_V_data_9_V_dout;
                data_250_V_5_fu_216 <= data_stream_V_data_10_V_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((trunc_ln203_reg_1552 = ap_const_lv4_B) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                data_247_V_8_fu_252 <= data_stream_V_data_7_V_dout;
                data_249_V_7_fu_248 <= data_stream_V_data_9_V_dout;
                data_250_V_6_fu_244 <= data_stream_V_data_10_V_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln41_fu_542_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                trunc_ln203_reg_1552 <= trunc_ln203_fu_554_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (real_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state5, icmp_ln41_fu_542_p2, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, grp_dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config11_s_fu_476_ap_done, io_acc_block_signal_op315)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_pp0_stage0 => 
                if (not(((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (icmp_ln41_fu_542_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1)))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (icmp_ln41_fu_542_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                if ((not(((io_acc_block_signal_op315 = ap_const_logic_0) or (grp_dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config11_s_fu_476_ap_done = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(1);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state4 <= ap_CS_fsm(2);
    ap_CS_fsm_state5 <= ap_CS_fsm(3);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, io_acc_block_signal_op170)
    begin
                ap_block_pp0_stage0_11001 <= ((io_acc_block_signal_op170 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, io_acc_block_signal_op170)
    begin
                ap_block_pp0_stage0_subdone <= ((io_acc_block_signal_op170 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_block_state1_assign_proc : process(real_start, ap_done_reg)
    begin
                ap_block_state1 <= ((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;

        ap_block_state2_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state3_pp0_stage0_iter1_assign_proc : process(io_acc_block_signal_op170)
    begin
                ap_block_state3_pp0_stage0_iter1 <= (io_acc_block_signal_op170 = ap_const_logic_0);
    end process;


    ap_condition_pp0_exit_iter0_state2_assign_proc : process(icmp_ln41_fu_542_p2)
    begin
        if ((icmp_ln41_fu_542_p2 = ap_const_lv1_1)) then 
            ap_condition_pp0_exit_iter0_state2 <= ap_const_logic_1;
        else 
            ap_condition_pp0_exit_iter0_state2 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state5, grp_dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config11_s_fu_476_ap_done, io_acc_block_signal_op315)
    begin
        if ((not(((io_acc_block_signal_op315 = ap_const_logic_0) or (grp_dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config11_s_fu_476_ap_done = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((real_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter0)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;

    data_stream_V_data_0_V_blk_n_assign_proc : process(data_stream_V_data_0_V_empty_n, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            data_stream_V_data_0_V_blk_n <= data_stream_V_data_0_V_empty_n;
        else 
            data_stream_V_data_0_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    data_stream_V_data_0_V_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            data_stream_V_data_0_V_read <= ap_const_logic_1;
        else 
            data_stream_V_data_0_V_read <= ap_const_logic_0;
        end if; 
    end process;


    data_stream_V_data_10_V_blk_n_assign_proc : process(data_stream_V_data_10_V_empty_n, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            data_stream_V_data_10_V_blk_n <= data_stream_V_data_10_V_empty_n;
        else 
            data_stream_V_data_10_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    data_stream_V_data_10_V_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            data_stream_V_data_10_V_read <= ap_const_logic_1;
        else 
            data_stream_V_data_10_V_read <= ap_const_logic_0;
        end if; 
    end process;


    data_stream_V_data_11_V_blk_n_assign_proc : process(data_stream_V_data_11_V_empty_n, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            data_stream_V_data_11_V_blk_n <= data_stream_V_data_11_V_empty_n;
        else 
            data_stream_V_data_11_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    data_stream_V_data_11_V_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            data_stream_V_data_11_V_read <= ap_const_logic_1;
        else 
            data_stream_V_data_11_V_read <= ap_const_logic_0;
        end if; 
    end process;


    data_stream_V_data_12_V_blk_n_assign_proc : process(data_stream_V_data_12_V_empty_n, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            data_stream_V_data_12_V_blk_n <= data_stream_V_data_12_V_empty_n;
        else 
            data_stream_V_data_12_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    data_stream_V_data_12_V_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            data_stream_V_data_12_V_read <= ap_const_logic_1;
        else 
            data_stream_V_data_12_V_read <= ap_const_logic_0;
        end if; 
    end process;


    data_stream_V_data_13_V_blk_n_assign_proc : process(data_stream_V_data_13_V_empty_n, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            data_stream_V_data_13_V_blk_n <= data_stream_V_data_13_V_empty_n;
        else 
            data_stream_V_data_13_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    data_stream_V_data_13_V_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            data_stream_V_data_13_V_read <= ap_const_logic_1;
        else 
            data_stream_V_data_13_V_read <= ap_const_logic_0;
        end if; 
    end process;


    data_stream_V_data_14_V_blk_n_assign_proc : process(data_stream_V_data_14_V_empty_n, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            data_stream_V_data_14_V_blk_n <= data_stream_V_data_14_V_empty_n;
        else 
            data_stream_V_data_14_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    data_stream_V_data_14_V_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            data_stream_V_data_14_V_read <= ap_const_logic_1;
        else 
            data_stream_V_data_14_V_read <= ap_const_logic_0;
        end if; 
    end process;


    data_stream_V_data_15_V_blk_n_assign_proc : process(data_stream_V_data_15_V_empty_n, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            data_stream_V_data_15_V_blk_n <= data_stream_V_data_15_V_empty_n;
        else 
            data_stream_V_data_15_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    data_stream_V_data_15_V_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            data_stream_V_data_15_V_read <= ap_const_logic_1;
        else 
            data_stream_V_data_15_V_read <= ap_const_logic_0;
        end if; 
    end process;


    data_stream_V_data_1_V_blk_n_assign_proc : process(data_stream_V_data_1_V_empty_n, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            data_stream_V_data_1_V_blk_n <= data_stream_V_data_1_V_empty_n;
        else 
            data_stream_V_data_1_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    data_stream_V_data_1_V_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            data_stream_V_data_1_V_read <= ap_const_logic_1;
        else 
            data_stream_V_data_1_V_read <= ap_const_logic_0;
        end if; 
    end process;


    data_stream_V_data_2_V_blk_n_assign_proc : process(data_stream_V_data_2_V_empty_n, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            data_stream_V_data_2_V_blk_n <= data_stream_V_data_2_V_empty_n;
        else 
            data_stream_V_data_2_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    data_stream_V_data_2_V_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            data_stream_V_data_2_V_read <= ap_const_logic_1;
        else 
            data_stream_V_data_2_V_read <= ap_const_logic_0;
        end if; 
    end process;


    data_stream_V_data_3_V_blk_n_assign_proc : process(data_stream_V_data_3_V_empty_n, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            data_stream_V_data_3_V_blk_n <= data_stream_V_data_3_V_empty_n;
        else 
            data_stream_V_data_3_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    data_stream_V_data_3_V_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            data_stream_V_data_3_V_read <= ap_const_logic_1;
        else 
            data_stream_V_data_3_V_read <= ap_const_logic_0;
        end if; 
    end process;


    data_stream_V_data_4_V_blk_n_assign_proc : process(data_stream_V_data_4_V_empty_n, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            data_stream_V_data_4_V_blk_n <= data_stream_V_data_4_V_empty_n;
        else 
            data_stream_V_data_4_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    data_stream_V_data_4_V_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            data_stream_V_data_4_V_read <= ap_const_logic_1;
        else 
            data_stream_V_data_4_V_read <= ap_const_logic_0;
        end if; 
    end process;


    data_stream_V_data_5_V_blk_n_assign_proc : process(data_stream_V_data_5_V_empty_n, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            data_stream_V_data_5_V_blk_n <= data_stream_V_data_5_V_empty_n;
        else 
            data_stream_V_data_5_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    data_stream_V_data_5_V_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            data_stream_V_data_5_V_read <= ap_const_logic_1;
        else 
            data_stream_V_data_5_V_read <= ap_const_logic_0;
        end if; 
    end process;


    data_stream_V_data_6_V_blk_n_assign_proc : process(data_stream_V_data_6_V_empty_n, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            data_stream_V_data_6_V_blk_n <= data_stream_V_data_6_V_empty_n;
        else 
            data_stream_V_data_6_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    data_stream_V_data_6_V_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            data_stream_V_data_6_V_read <= ap_const_logic_1;
        else 
            data_stream_V_data_6_V_read <= ap_const_logic_0;
        end if; 
    end process;


    data_stream_V_data_7_V_blk_n_assign_proc : process(data_stream_V_data_7_V_empty_n, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            data_stream_V_data_7_V_blk_n <= data_stream_V_data_7_V_empty_n;
        else 
            data_stream_V_data_7_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    data_stream_V_data_7_V_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            data_stream_V_data_7_V_read <= ap_const_logic_1;
        else 
            data_stream_V_data_7_V_read <= ap_const_logic_0;
        end if; 
    end process;


    data_stream_V_data_8_V_blk_n_assign_proc : process(data_stream_V_data_8_V_empty_n, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            data_stream_V_data_8_V_blk_n <= data_stream_V_data_8_V_empty_n;
        else 
            data_stream_V_data_8_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    data_stream_V_data_8_V_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            data_stream_V_data_8_V_read <= ap_const_logic_1;
        else 
            data_stream_V_data_8_V_read <= ap_const_logic_0;
        end if; 
    end process;


    data_stream_V_data_9_V_blk_n_assign_proc : process(data_stream_V_data_9_V_empty_n, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            data_stream_V_data_9_V_blk_n <= data_stream_V_data_9_V_empty_n;
        else 
            data_stream_V_data_9_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    data_stream_V_data_9_V_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            data_stream_V_data_9_V_read <= ap_const_logic_1;
        else 
            data_stream_V_data_9_V_read <= ap_const_logic_0;
        end if; 
    end process;

    grp_dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config11_s_fu_476_ap_start <= grp_dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config11_s_fu_476_ap_start_reg;
    i_in_fu_548_p2 <= std_logic_vector(unsigned(i_in_0_reg_465) + unsigned(ap_const_lv5_1));
    icmp_ln41_fu_542_p2 <= "1" when (i_in_0_reg_465 = ap_const_lv5_10) else "0";

    internal_ap_ready_assign_proc : process(ap_CS_fsm_state5, grp_dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config11_s_fu_476_ap_done, io_acc_block_signal_op315)
    begin
        if ((not(((io_acc_block_signal_op315 = ap_const_logic_0) or (grp_dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config11_s_fu_476_ap_done = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    io_acc_block_signal_op170 <= (data_stream_V_data_9_V_empty_n and data_stream_V_data_8_V_empty_n and data_stream_V_data_7_V_empty_n and data_stream_V_data_6_V_empty_n and data_stream_V_data_5_V_empty_n and data_stream_V_data_4_V_empty_n and data_stream_V_data_3_V_empty_n and data_stream_V_data_2_V_empty_n and data_stream_V_data_1_V_empty_n and data_stream_V_data_15_V_empty_n and data_stream_V_data_14_V_empty_n and data_stream_V_data_13_V_empty_n and data_stream_V_data_12_V_empty_n and data_stream_V_data_11_V_empty_n and data_stream_V_data_10_V_empty_n and data_stream_V_data_0_V_empty_n);
    io_acc_block_signal_op315 <= (res_stream_V_data_9_V_full_n and res_stream_V_data_8_V_full_n and res_stream_V_data_7_V_full_n and res_stream_V_data_6_V_full_n and res_stream_V_data_5_V_full_n and res_stream_V_data_4_V_full_n and res_stream_V_data_3_V_full_n and res_stream_V_data_2_V_full_n and res_stream_V_data_1_V_full_n and res_stream_V_data_11_V_full_n and res_stream_V_data_10_V_full_n and res_stream_V_data_0_V_full_n);

    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;


    res_stream_V_data_0_V_blk_n_assign_proc : process(res_stream_V_data_0_V_full_n, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            res_stream_V_data_0_V_blk_n <= res_stream_V_data_0_V_full_n;
        else 
            res_stream_V_data_0_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    res_stream_V_data_0_V_din <= ap_const_lv27_0;

    res_stream_V_data_0_V_write_assign_proc : process(ap_CS_fsm_state5, grp_dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config11_s_fu_476_ap_done, io_acc_block_signal_op315)
    begin
        if ((not(((io_acc_block_signal_op315 = ap_const_logic_0) or (grp_dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config11_s_fu_476_ap_done = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            res_stream_V_data_0_V_write <= ap_const_logic_1;
        else 
            res_stream_V_data_0_V_write <= ap_const_logic_0;
        end if; 
    end process;


    res_stream_V_data_10_V_blk_n_assign_proc : process(res_stream_V_data_10_V_full_n, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            res_stream_V_data_10_V_blk_n <= res_stream_V_data_10_V_full_n;
        else 
            res_stream_V_data_10_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    res_stream_V_data_10_V_din <= grp_dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config11_s_fu_476_ap_return_6;

    res_stream_V_data_10_V_write_assign_proc : process(ap_CS_fsm_state5, grp_dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config11_s_fu_476_ap_done, io_acc_block_signal_op315)
    begin
        if ((not(((io_acc_block_signal_op315 = ap_const_logic_0) or (grp_dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config11_s_fu_476_ap_done = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            res_stream_V_data_10_V_write <= ap_const_logic_1;
        else 
            res_stream_V_data_10_V_write <= ap_const_logic_0;
        end if; 
    end process;


    res_stream_V_data_11_V_blk_n_assign_proc : process(res_stream_V_data_11_V_full_n, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            res_stream_V_data_11_V_blk_n <= res_stream_V_data_11_V_full_n;
        else 
            res_stream_V_data_11_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    res_stream_V_data_11_V_din <= ap_const_lv27_0;

    res_stream_V_data_11_V_write_assign_proc : process(ap_CS_fsm_state5, grp_dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config11_s_fu_476_ap_done, io_acc_block_signal_op315)
    begin
        if ((not(((io_acc_block_signal_op315 = ap_const_logic_0) or (grp_dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config11_s_fu_476_ap_done = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            res_stream_V_data_11_V_write <= ap_const_logic_1;
        else 
            res_stream_V_data_11_V_write <= ap_const_logic_0;
        end if; 
    end process;


    res_stream_V_data_1_V_blk_n_assign_proc : process(res_stream_V_data_1_V_full_n, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            res_stream_V_data_1_V_blk_n <= res_stream_V_data_1_V_full_n;
        else 
            res_stream_V_data_1_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    res_stream_V_data_1_V_din <= ap_const_lv27_0;

    res_stream_V_data_1_V_write_assign_proc : process(ap_CS_fsm_state5, grp_dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config11_s_fu_476_ap_done, io_acc_block_signal_op315)
    begin
        if ((not(((io_acc_block_signal_op315 = ap_const_logic_0) or (grp_dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config11_s_fu_476_ap_done = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            res_stream_V_data_1_V_write <= ap_const_logic_1;
        else 
            res_stream_V_data_1_V_write <= ap_const_logic_0;
        end if; 
    end process;


    res_stream_V_data_2_V_blk_n_assign_proc : process(res_stream_V_data_2_V_full_n, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            res_stream_V_data_2_V_blk_n <= res_stream_V_data_2_V_full_n;
        else 
            res_stream_V_data_2_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    res_stream_V_data_2_V_din <= grp_dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config11_s_fu_476_ap_return_0;

    res_stream_V_data_2_V_write_assign_proc : process(ap_CS_fsm_state5, grp_dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config11_s_fu_476_ap_done, io_acc_block_signal_op315)
    begin
        if ((not(((io_acc_block_signal_op315 = ap_const_logic_0) or (grp_dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config11_s_fu_476_ap_done = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            res_stream_V_data_2_V_write <= ap_const_logic_1;
        else 
            res_stream_V_data_2_V_write <= ap_const_logic_0;
        end if; 
    end process;


    res_stream_V_data_3_V_blk_n_assign_proc : process(res_stream_V_data_3_V_full_n, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            res_stream_V_data_3_V_blk_n <= res_stream_V_data_3_V_full_n;
        else 
            res_stream_V_data_3_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    res_stream_V_data_3_V_din <= ap_const_lv27_0;

    res_stream_V_data_3_V_write_assign_proc : process(ap_CS_fsm_state5, grp_dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config11_s_fu_476_ap_done, io_acc_block_signal_op315)
    begin
        if ((not(((io_acc_block_signal_op315 = ap_const_logic_0) or (grp_dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config11_s_fu_476_ap_done = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            res_stream_V_data_3_V_write <= ap_const_logic_1;
        else 
            res_stream_V_data_3_V_write <= ap_const_logic_0;
        end if; 
    end process;


    res_stream_V_data_4_V_blk_n_assign_proc : process(res_stream_V_data_4_V_full_n, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            res_stream_V_data_4_V_blk_n <= res_stream_V_data_4_V_full_n;
        else 
            res_stream_V_data_4_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    res_stream_V_data_4_V_din <= grp_dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config11_s_fu_476_ap_return_1;

    res_stream_V_data_4_V_write_assign_proc : process(ap_CS_fsm_state5, grp_dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config11_s_fu_476_ap_done, io_acc_block_signal_op315)
    begin
        if ((not(((io_acc_block_signal_op315 = ap_const_logic_0) or (grp_dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config11_s_fu_476_ap_done = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            res_stream_V_data_4_V_write <= ap_const_logic_1;
        else 
            res_stream_V_data_4_V_write <= ap_const_logic_0;
        end if; 
    end process;


    res_stream_V_data_5_V_blk_n_assign_proc : process(res_stream_V_data_5_V_full_n, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            res_stream_V_data_5_V_blk_n <= res_stream_V_data_5_V_full_n;
        else 
            res_stream_V_data_5_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    res_stream_V_data_5_V_din <= ap_const_lv27_0;

    res_stream_V_data_5_V_write_assign_proc : process(ap_CS_fsm_state5, grp_dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config11_s_fu_476_ap_done, io_acc_block_signal_op315)
    begin
        if ((not(((io_acc_block_signal_op315 = ap_const_logic_0) or (grp_dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config11_s_fu_476_ap_done = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            res_stream_V_data_5_V_write <= ap_const_logic_1;
        else 
            res_stream_V_data_5_V_write <= ap_const_logic_0;
        end if; 
    end process;


    res_stream_V_data_6_V_blk_n_assign_proc : process(res_stream_V_data_6_V_full_n, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            res_stream_V_data_6_V_blk_n <= res_stream_V_data_6_V_full_n;
        else 
            res_stream_V_data_6_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    res_stream_V_data_6_V_din <= grp_dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config11_s_fu_476_ap_return_2;

    res_stream_V_data_6_V_write_assign_proc : process(ap_CS_fsm_state5, grp_dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config11_s_fu_476_ap_done, io_acc_block_signal_op315)
    begin
        if ((not(((io_acc_block_signal_op315 = ap_const_logic_0) or (grp_dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config11_s_fu_476_ap_done = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            res_stream_V_data_6_V_write <= ap_const_logic_1;
        else 
            res_stream_V_data_6_V_write <= ap_const_logic_0;
        end if; 
    end process;


    res_stream_V_data_7_V_blk_n_assign_proc : process(res_stream_V_data_7_V_full_n, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            res_stream_V_data_7_V_blk_n <= res_stream_V_data_7_V_full_n;
        else 
            res_stream_V_data_7_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    res_stream_V_data_7_V_din <= grp_dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config11_s_fu_476_ap_return_3;

    res_stream_V_data_7_V_write_assign_proc : process(ap_CS_fsm_state5, grp_dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config11_s_fu_476_ap_done, io_acc_block_signal_op315)
    begin
        if ((not(((io_acc_block_signal_op315 = ap_const_logic_0) or (grp_dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config11_s_fu_476_ap_done = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            res_stream_V_data_7_V_write <= ap_const_logic_1;
        else 
            res_stream_V_data_7_V_write <= ap_const_logic_0;
        end if; 
    end process;


    res_stream_V_data_8_V_blk_n_assign_proc : process(res_stream_V_data_8_V_full_n, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            res_stream_V_data_8_V_blk_n <= res_stream_V_data_8_V_full_n;
        else 
            res_stream_V_data_8_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    res_stream_V_data_8_V_din <= grp_dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config11_s_fu_476_ap_return_4;

    res_stream_V_data_8_V_write_assign_proc : process(ap_CS_fsm_state5, grp_dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config11_s_fu_476_ap_done, io_acc_block_signal_op315)
    begin
        if ((not(((io_acc_block_signal_op315 = ap_const_logic_0) or (grp_dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config11_s_fu_476_ap_done = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            res_stream_V_data_8_V_write <= ap_const_logic_1;
        else 
            res_stream_V_data_8_V_write <= ap_const_logic_0;
        end if; 
    end process;


    res_stream_V_data_9_V_blk_n_assign_proc : process(res_stream_V_data_9_V_full_n, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            res_stream_V_data_9_V_blk_n <= res_stream_V_data_9_V_full_n;
        else 
            res_stream_V_data_9_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    res_stream_V_data_9_V_din <= grp_dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config11_s_fu_476_ap_return_5;

    res_stream_V_data_9_V_write_assign_proc : process(ap_CS_fsm_state5, grp_dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config11_s_fu_476_ap_done, io_acc_block_signal_op315)
    begin
        if ((not(((io_acc_block_signal_op315 = ap_const_logic_0) or (grp_dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config11_s_fu_476_ap_done = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            res_stream_V_data_9_V_write <= ap_const_logic_1;
        else 
            res_stream_V_data_9_V_write <= ap_const_logic_0;
        end if; 
    end process;

    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

    trunc_ln203_fu_554_p1 <= i_in_0_reg_465(4 - 1 downto 0);
end behav;
