-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2020.1
-- Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config13_s is
port (
    ap_ready : OUT STD_LOGIC;
    data_2_V_read : IN STD_LOGIC_VECTOR (26 downto 0);
    data_4_V_read : IN STD_LOGIC_VECTOR (26 downto 0);
    data_6_V_read : IN STD_LOGIC_VECTOR (26 downto 0);
    data_7_V_read : IN STD_LOGIC_VECTOR (26 downto 0);
    data_8_V_read : IN STD_LOGIC_VECTOR (26 downto 0);
    data_9_V_read : IN STD_LOGIC_VECTOR (26 downto 0);
    data_10_V_read : IN STD_LOGIC_VECTOR (26 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (26 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (26 downto 0) );
end;


architecture behav of dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config13_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv27_A000 : STD_LOGIC_VECTOR (26 downto 0) := "000000000001010000000000000";
    constant ap_const_lv27_7FF6000 : STD_LOGIC_VECTOR (26 downto 0) := "111111111110110000000000000";
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal sext_ln1118_fu_76_p0 : STD_LOGIC_VECTOR (26 downto 0);
    signal shl_ln_fu_80_p1 : STD_LOGIC_VECTOR (26 downto 0);
    signal shl_ln_fu_80_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln1118_fu_88_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln1118_1_fu_104_p0 : STD_LOGIC_VECTOR (26 downto 0);
    signal shl_ln1118_s_fu_108_p1 : STD_LOGIC_VECTOR (26 downto 0);
    signal shl_ln1118_s_fu_108_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln1118_1_fu_104_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln1118_1_fu_116_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln1118_2_fu_132_p0 : STD_LOGIC_VECTOR (26 downto 0);
    signal shl_ln1118_1_fu_136_p1 : STD_LOGIC_VECTOR (26 downto 0);
    signal shl_ln1118_1_fu_136_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln1118_2_fu_144_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln1118_3_fu_160_p0 : STD_LOGIC_VECTOR (26 downto 0);
    signal shl_ln1118_2_fu_164_p1 : STD_LOGIC_VECTOR (26 downto 0);
    signal shl_ln1118_2_fu_164_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln1118_3_fu_160_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln1118_3_fu_172_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln1118_4_fu_188_p0 : STD_LOGIC_VECTOR (26 downto 0);
    signal shl_ln1118_3_fu_192_p1 : STD_LOGIC_VECTOR (26 downto 0);
    signal shl_ln1118_3_fu_192_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln1118_4_fu_188_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln1118_4_fu_200_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln1118_5_fu_216_p0 : STD_LOGIC_VECTOR (26 downto 0);
    signal shl_ln1118_4_fu_220_p1 : STD_LOGIC_VECTOR (26 downto 0);
    signal shl_ln1118_4_fu_220_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln1118_5_fu_216_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln1118_5_fu_228_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln1118_6_fu_244_p0 : STD_LOGIC_VECTOR (26 downto 0);
    signal shl_ln1118_5_fu_248_p1 : STD_LOGIC_VECTOR (26 downto 0);
    signal shl_ln1118_5_fu_248_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln1118_6_fu_244_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln1118_6_fu_256_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln708_s_fu_122_p4 : STD_LOGIC_VECTOR (26 downto 0);
    signal trunc_ln_fu_94_p4 : STD_LOGIC_VECTOR (26 downto 0);
    signal trunc_ln708_2_fu_178_p4 : STD_LOGIC_VECTOR (26 downto 0);
    signal trunc_ln708_1_fu_150_p4 : STD_LOGIC_VECTOR (26 downto 0);
    signal add_ln703_fu_272_p2 : STD_LOGIC_VECTOR (26 downto 0);
    signal add_ln703_1_fu_278_p2 : STD_LOGIC_VECTOR (26 downto 0);
    signal trunc_ln708_4_fu_234_p4 : STD_LOGIC_VECTOR (26 downto 0);
    signal trunc_ln708_3_fu_206_p4 : STD_LOGIC_VECTOR (26 downto 0);
    signal trunc_ln708_5_fu_262_p4 : STD_LOGIC_VECTOR (26 downto 0);
    signal add_ln703_3_fu_290_p2 : STD_LOGIC_VECTOR (26 downto 0);
    signal add_ln703_4_fu_296_p2 : STD_LOGIC_VECTOR (26 downto 0);
    signal add_ln703_2_fu_284_p2 : STD_LOGIC_VECTOR (26 downto 0);
    signal add_ln703_5_fu_302_p2 : STD_LOGIC_VECTOR (26 downto 0);
    signal sext_ln1118_fu_76_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln1118_7_fu_314_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln1118_8_fu_330_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln1118_2_fu_132_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln1118_9_fu_346_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln1118_10_fu_362_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln1118_11_fu_378_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln1118_12_fu_394_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln1118_13_fu_410_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln708_7_fu_336_p4 : STD_LOGIC_VECTOR (26 downto 0);
    signal trunc_ln708_6_fu_320_p4 : STD_LOGIC_VECTOR (26 downto 0);
    signal trunc_ln708_9_fu_368_p4 : STD_LOGIC_VECTOR (26 downto 0);
    signal trunc_ln708_8_fu_352_p4 : STD_LOGIC_VECTOR (26 downto 0);
    signal add_ln703_7_fu_426_p2 : STD_LOGIC_VECTOR (26 downto 0);
    signal add_ln703_8_fu_432_p2 : STD_LOGIC_VECTOR (26 downto 0);
    signal trunc_ln708_11_fu_400_p4 : STD_LOGIC_VECTOR (26 downto 0);
    signal trunc_ln708_10_fu_384_p4 : STD_LOGIC_VECTOR (26 downto 0);
    signal trunc_ln708_12_fu_416_p4 : STD_LOGIC_VECTOR (26 downto 0);
    signal add_ln703_10_fu_444_p2 : STD_LOGIC_VECTOR (26 downto 0);
    signal add_ln703_11_fu_450_p2 : STD_LOGIC_VECTOR (26 downto 0);
    signal add_ln703_9_fu_438_p2 : STD_LOGIC_VECTOR (26 downto 0);
    signal add_ln703_12_fu_456_p2 : STD_LOGIC_VECTOR (26 downto 0);
    signal add_ln703_6_fu_308_p2 : STD_LOGIC_VECTOR (26 downto 0);
    signal acc_1_V_fu_462_p2 : STD_LOGIC_VECTOR (26 downto 0);


begin



    acc_1_V_fu_462_p2 <= std_logic_vector(unsigned(add_ln703_9_fu_438_p2) + unsigned(add_ln703_12_fu_456_p2));
    add_ln703_10_fu_444_p2 <= std_logic_vector(unsigned(trunc_ln708_11_fu_400_p4) + unsigned(trunc_ln708_10_fu_384_p4));
    add_ln703_11_fu_450_p2 <= std_logic_vector(unsigned(trunc_ln708_12_fu_416_p4) + unsigned(ap_const_lv27_7FF6000));
    add_ln703_12_fu_456_p2 <= std_logic_vector(unsigned(add_ln703_10_fu_444_p2) + unsigned(add_ln703_11_fu_450_p2));
    add_ln703_1_fu_278_p2 <= std_logic_vector(unsigned(trunc_ln708_2_fu_178_p4) + unsigned(trunc_ln708_1_fu_150_p4));
    add_ln703_2_fu_284_p2 <= std_logic_vector(unsigned(add_ln703_fu_272_p2) + unsigned(add_ln703_1_fu_278_p2));
    add_ln703_3_fu_290_p2 <= std_logic_vector(unsigned(trunc_ln708_4_fu_234_p4) + unsigned(trunc_ln708_3_fu_206_p4));
    add_ln703_4_fu_296_p2 <= std_logic_vector(unsigned(trunc_ln708_5_fu_262_p4) + unsigned(ap_const_lv27_A000));
    add_ln703_5_fu_302_p2 <= std_logic_vector(unsigned(add_ln703_3_fu_290_p2) + unsigned(add_ln703_4_fu_296_p2));
    add_ln703_6_fu_308_p2 <= std_logic_vector(unsigned(add_ln703_2_fu_284_p2) + unsigned(add_ln703_5_fu_302_p2));
    add_ln703_7_fu_426_p2 <= std_logic_vector(unsigned(trunc_ln708_7_fu_336_p4) + unsigned(trunc_ln708_6_fu_320_p4));
    add_ln703_8_fu_432_p2 <= std_logic_vector(unsigned(trunc_ln708_9_fu_368_p4) + unsigned(trunc_ln708_8_fu_352_p4));
    add_ln703_9_fu_438_p2 <= std_logic_vector(unsigned(add_ln703_7_fu_426_p2) + unsigned(add_ln703_8_fu_432_p2));
    add_ln703_fu_272_p2 <= std_logic_vector(unsigned(trunc_ln708_s_fu_122_p4) + unsigned(trunc_ln_fu_94_p4));
    ap_ready <= ap_const_logic_1;
    ap_return_0 <= add_ln703_6_fu_308_p2;
    ap_return_1 <= acc_1_V_fu_462_p2;
    sext_ln1118_1_fu_104_p0 <= data_4_V_read;
        sext_ln1118_1_fu_104_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln1118_1_fu_104_p0),32));

    sext_ln1118_2_fu_132_p0 <= data_6_V_read;
        sext_ln1118_2_fu_132_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln1118_2_fu_132_p0),32));

    sext_ln1118_3_fu_160_p0 <= data_7_V_read;
        sext_ln1118_3_fu_160_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln1118_3_fu_160_p0),32));

    sext_ln1118_4_fu_188_p0 <= data_8_V_read;
        sext_ln1118_4_fu_188_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln1118_4_fu_188_p0),32));

    sext_ln1118_5_fu_216_p0 <= data_9_V_read;
        sext_ln1118_5_fu_216_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln1118_5_fu_216_p0),32));

    sext_ln1118_6_fu_244_p0 <= data_10_V_read;
        sext_ln1118_6_fu_244_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln1118_6_fu_244_p0),32));

    sext_ln1118_fu_76_p0 <= data_2_V_read;
        sext_ln1118_fu_76_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln1118_fu_76_p0),32));

    shl_ln1118_1_fu_136_p1 <= data_6_V_read;
    shl_ln1118_1_fu_136_p3 <= (shl_ln1118_1_fu_136_p1 & ap_const_lv5_0);
    shl_ln1118_2_fu_164_p1 <= data_7_V_read;
    shl_ln1118_2_fu_164_p3 <= (shl_ln1118_2_fu_164_p1 & ap_const_lv5_0);
    shl_ln1118_3_fu_192_p1 <= data_8_V_read;
    shl_ln1118_3_fu_192_p3 <= (shl_ln1118_3_fu_192_p1 & ap_const_lv5_0);
    shl_ln1118_4_fu_220_p1 <= data_9_V_read;
    shl_ln1118_4_fu_220_p3 <= (shl_ln1118_4_fu_220_p1 & ap_const_lv5_0);
    shl_ln1118_5_fu_248_p1 <= data_10_V_read;
    shl_ln1118_5_fu_248_p3 <= (shl_ln1118_5_fu_248_p1 & ap_const_lv5_0);
    shl_ln1118_s_fu_108_p1 <= data_4_V_read;
    shl_ln1118_s_fu_108_p3 <= (shl_ln1118_s_fu_108_p1 & ap_const_lv5_0);
    shl_ln_fu_80_p1 <= data_2_V_read;
    shl_ln_fu_80_p3 <= (shl_ln_fu_80_p1 & ap_const_lv5_0);
    sub_ln1118_10_fu_362_p2 <= std_logic_vector(unsigned(ap_const_lv32_0) - unsigned(shl_ln1118_2_fu_164_p3));
    sub_ln1118_11_fu_378_p2 <= std_logic_vector(unsigned(ap_const_lv32_0) - unsigned(shl_ln1118_3_fu_192_p3));
    sub_ln1118_12_fu_394_p2 <= std_logic_vector(unsigned(ap_const_lv32_0) - unsigned(shl_ln1118_4_fu_220_p3));
    sub_ln1118_13_fu_410_p2 <= std_logic_vector(unsigned(ap_const_lv32_0) - unsigned(shl_ln1118_5_fu_248_p3));
    sub_ln1118_1_fu_116_p2 <= std_logic_vector(unsigned(shl_ln1118_s_fu_108_p3) - unsigned(sext_ln1118_1_fu_104_p1));
    sub_ln1118_2_fu_144_p2 <= std_logic_vector(unsigned(ap_const_lv32_0) - unsigned(shl_ln1118_1_fu_136_p3));
    sub_ln1118_3_fu_172_p2 <= std_logic_vector(unsigned(shl_ln1118_2_fu_164_p3) - unsigned(sext_ln1118_3_fu_160_p1));
    sub_ln1118_4_fu_200_p2 <= std_logic_vector(unsigned(shl_ln1118_3_fu_192_p3) - unsigned(sext_ln1118_4_fu_188_p1));
    sub_ln1118_5_fu_228_p2 <= std_logic_vector(unsigned(shl_ln1118_4_fu_220_p3) - unsigned(sext_ln1118_5_fu_216_p1));
    sub_ln1118_6_fu_256_p2 <= std_logic_vector(unsigned(shl_ln1118_5_fu_248_p3) - unsigned(sext_ln1118_6_fu_244_p1));
    sub_ln1118_7_fu_314_p2 <= std_logic_vector(unsigned(shl_ln_fu_80_p3) - unsigned(sext_ln1118_fu_76_p1));
    sub_ln1118_8_fu_330_p2 <= std_logic_vector(unsigned(ap_const_lv32_0) - unsigned(shl_ln1118_s_fu_108_p3));
    sub_ln1118_9_fu_346_p2 <= std_logic_vector(unsigned(shl_ln1118_1_fu_136_p3) - unsigned(sext_ln1118_2_fu_132_p1));
    sub_ln1118_fu_88_p2 <= std_logic_vector(unsigned(ap_const_lv32_0) - unsigned(shl_ln_fu_80_p3));
    trunc_ln708_10_fu_384_p4 <= sub_ln1118_11_fu_378_p2(31 downto 5);
    trunc_ln708_11_fu_400_p4 <= sub_ln1118_12_fu_394_p2(31 downto 5);
    trunc_ln708_12_fu_416_p4 <= sub_ln1118_13_fu_410_p2(31 downto 5);
    trunc_ln708_1_fu_150_p4 <= sub_ln1118_2_fu_144_p2(31 downto 5);
    trunc_ln708_2_fu_178_p4 <= sub_ln1118_3_fu_172_p2(31 downto 5);
    trunc_ln708_3_fu_206_p4 <= sub_ln1118_4_fu_200_p2(31 downto 5);
    trunc_ln708_4_fu_234_p4 <= sub_ln1118_5_fu_228_p2(31 downto 5);
    trunc_ln708_5_fu_262_p4 <= sub_ln1118_6_fu_256_p2(31 downto 5);
    trunc_ln708_6_fu_320_p4 <= sub_ln1118_7_fu_314_p2(31 downto 5);
    trunc_ln708_7_fu_336_p4 <= sub_ln1118_8_fu_330_p2(31 downto 5);
    trunc_ln708_8_fu_352_p4 <= sub_ln1118_9_fu_346_p2(31 downto 5);
    trunc_ln708_9_fu_368_p4 <= sub_ln1118_10_fu_362_p2(31 downto 5);
    trunc_ln708_s_fu_122_p4 <= sub_ln1118_1_fu_116_p2(31 downto 5);
    trunc_ln_fu_94_p4 <= sub_ln1118_fu_88_p2(31 downto 5);
end behav;
