-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2020.1
-- Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity reduce_ap_fixed_16_Op_max_ap_fixed_27_9_4_0_0_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    x_0_V_read : IN STD_LOGIC_VECTOR (26 downto 0);
    x_1_V_read : IN STD_LOGIC_VECTOR (26 downto 0);
    x_2_V_read : IN STD_LOGIC_VECTOR (26 downto 0);
    x_3_V_read : IN STD_LOGIC_VECTOR (26 downto 0);
    x_4_V_read : IN STD_LOGIC_VECTOR (26 downto 0);
    x_5_V_read : IN STD_LOGIC_VECTOR (26 downto 0);
    x_6_V_read : IN STD_LOGIC_VECTOR (26 downto 0);
    x_7_V_read : IN STD_LOGIC_VECTOR (26 downto 0);
    x_8_V_read : IN STD_LOGIC_VECTOR (26 downto 0);
    x_9_V_read : IN STD_LOGIC_VECTOR (26 downto 0);
    x_10_V_read : IN STD_LOGIC_VECTOR (26 downto 0);
    x_11_V_read : IN STD_LOGIC_VECTOR (26 downto 0);
    x_12_V_read : IN STD_LOGIC_VECTOR (26 downto 0);
    x_13_V_read : IN STD_LOGIC_VECTOR (26 downto 0);
    x_14_V_read : IN STD_LOGIC_VECTOR (26 downto 0);
    x_15_V_read : IN STD_LOGIC_VECTOR (26 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (26 downto 0);
    ap_ce : IN STD_LOGIC );
end;


architecture behav of reduce_ap_fixed_16_Op_max_ap_fixed_27_9_4_0_0_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;

    signal select_ln86_12_fu_220_p3 : STD_LOGIC_VECTOR (26 downto 0);
    signal select_ln86_12_reg_336 : STD_LOGIC_VECTOR (26 downto 0);
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal select_ln86_19_fu_318_p3 : STD_LOGIC_VECTOR (26 downto 0);
    signal select_ln86_19_reg_342 : STD_LOGIC_VECTOR (26 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal icmp_ln1496_fu_130_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1496_7_fu_144_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln86_fu_136_p3 : STD_LOGIC_VECTOR (26 downto 0);
    signal select_ln86_7_fu_150_p3 : STD_LOGIC_VECTOR (26 downto 0);
    signal icmp_ln1496_8_fu_158_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1496_9_fu_172_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1496_10_fu_186_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln86_9_fu_178_p3 : STD_LOGIC_VECTOR (26 downto 0);
    signal select_ln86_10_fu_192_p3 : STD_LOGIC_VECTOR (26 downto 0);
    signal icmp_ln1496_11_fu_200_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln86_8_fu_164_p3 : STD_LOGIC_VECTOR (26 downto 0);
    signal select_ln86_11_fu_206_p3 : STD_LOGIC_VECTOR (26 downto 0);
    signal icmp_ln1496_12_fu_214_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1496_13_fu_228_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1496_14_fu_242_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln86_13_fu_234_p3 : STD_LOGIC_VECTOR (26 downto 0);
    signal select_ln86_14_fu_248_p3 : STD_LOGIC_VECTOR (26 downto 0);
    signal icmp_ln1496_15_fu_256_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1496_16_fu_270_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1496_17_fu_284_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln86_16_fu_276_p3 : STD_LOGIC_VECTOR (26 downto 0);
    signal select_ln86_17_fu_290_p3 : STD_LOGIC_VECTOR (26 downto 0);
    signal icmp_ln1496_18_fu_298_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln86_15_fu_262_p3 : STD_LOGIC_VECTOR (26 downto 0);
    signal select_ln86_18_fu_304_p3 : STD_LOGIC_VECTOR (26 downto 0);
    signal icmp_ln1496_19_fu_312_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1496_20_fu_326_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln86_20_fu_330_p3 : STD_LOGIC_VECTOR (26 downto 0);
    signal ap_ce_reg : STD_LOGIC;
    signal ap_return_int_reg : STD_LOGIC_VECTOR (26 downto 0);


begin




    ap_ce_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            ap_ce_reg <= ap_ce;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_ce_reg)) then
                ap_return_int_reg <= select_ln86_20_fu_330_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_const_logic_1))) then
                select_ln86_12_reg_336 <= select_ln86_12_fu_220_p3;
                select_ln86_19_reg_342 <= select_ln86_19_fu_318_p3;
            end if;
        end if;
    end process;
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_return_assign_proc : process(select_ln86_20_fu_330_p3, ap_ce_reg, ap_return_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return <= ap_return_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return <= select_ln86_20_fu_330_p3;
        end if; 
    end process;

    icmp_ln1496_10_fu_186_p2 <= "1" when (signed(x_6_V_read) < signed(x_7_V_read)) else "0";
    icmp_ln1496_11_fu_200_p2 <= "1" when (signed(select_ln86_9_fu_178_p3) < signed(select_ln86_10_fu_192_p3)) else "0";
    icmp_ln1496_12_fu_214_p2 <= "1" when (signed(select_ln86_8_fu_164_p3) < signed(select_ln86_11_fu_206_p3)) else "0";
    icmp_ln1496_13_fu_228_p2 <= "1" when (signed(x_8_V_read) < signed(x_9_V_read)) else "0";
    icmp_ln1496_14_fu_242_p2 <= "1" when (signed(x_10_V_read) < signed(x_11_V_read)) else "0";
    icmp_ln1496_15_fu_256_p2 <= "1" when (signed(select_ln86_13_fu_234_p3) < signed(select_ln86_14_fu_248_p3)) else "0";
    icmp_ln1496_16_fu_270_p2 <= "1" when (signed(x_12_V_read) < signed(x_13_V_read)) else "0";
    icmp_ln1496_17_fu_284_p2 <= "1" when (signed(x_14_V_read) < signed(x_15_V_read)) else "0";
    icmp_ln1496_18_fu_298_p2 <= "1" when (signed(select_ln86_16_fu_276_p3) < signed(select_ln86_17_fu_290_p3)) else "0";
    icmp_ln1496_19_fu_312_p2 <= "1" when (signed(select_ln86_15_fu_262_p3) < signed(select_ln86_18_fu_304_p3)) else "0";
    icmp_ln1496_20_fu_326_p2 <= "1" when (signed(select_ln86_12_reg_336) < signed(select_ln86_19_reg_342)) else "0";
    icmp_ln1496_7_fu_144_p2 <= "1" when (signed(x_2_V_read) < signed(x_3_V_read)) else "0";
    icmp_ln1496_8_fu_158_p2 <= "1" when (signed(select_ln86_fu_136_p3) < signed(select_ln86_7_fu_150_p3)) else "0";
    icmp_ln1496_9_fu_172_p2 <= "1" when (signed(x_4_V_read) < signed(x_5_V_read)) else "0";
    icmp_ln1496_fu_130_p2 <= "1" when (signed(x_0_V_read) < signed(x_1_V_read)) else "0";
    select_ln86_10_fu_192_p3 <= 
        x_7_V_read when (icmp_ln1496_10_fu_186_p2(0) = '1') else 
        x_6_V_read;
    select_ln86_11_fu_206_p3 <= 
        select_ln86_10_fu_192_p3 when (icmp_ln1496_11_fu_200_p2(0) = '1') else 
        select_ln86_9_fu_178_p3;
    select_ln86_12_fu_220_p3 <= 
        select_ln86_11_fu_206_p3 when (icmp_ln1496_12_fu_214_p2(0) = '1') else 
        select_ln86_8_fu_164_p3;
    select_ln86_13_fu_234_p3 <= 
        x_9_V_read when (icmp_ln1496_13_fu_228_p2(0) = '1') else 
        x_8_V_read;
    select_ln86_14_fu_248_p3 <= 
        x_11_V_read when (icmp_ln1496_14_fu_242_p2(0) = '1') else 
        x_10_V_read;
    select_ln86_15_fu_262_p3 <= 
        select_ln86_14_fu_248_p3 when (icmp_ln1496_15_fu_256_p2(0) = '1') else 
        select_ln86_13_fu_234_p3;
    select_ln86_16_fu_276_p3 <= 
        x_13_V_read when (icmp_ln1496_16_fu_270_p2(0) = '1') else 
        x_12_V_read;
    select_ln86_17_fu_290_p3 <= 
        x_15_V_read when (icmp_ln1496_17_fu_284_p2(0) = '1') else 
        x_14_V_read;
    select_ln86_18_fu_304_p3 <= 
        select_ln86_17_fu_290_p3 when (icmp_ln1496_18_fu_298_p2(0) = '1') else 
        select_ln86_16_fu_276_p3;
    select_ln86_19_fu_318_p3 <= 
        select_ln86_18_fu_304_p3 when (icmp_ln1496_19_fu_312_p2(0) = '1') else 
        select_ln86_15_fu_262_p3;
    select_ln86_20_fu_330_p3 <= 
        select_ln86_19_reg_342 when (icmp_ln1496_20_fu_326_p2(0) = '1') else 
        select_ln86_12_reg_336;
    select_ln86_7_fu_150_p3 <= 
        x_3_V_read when (icmp_ln1496_7_fu_144_p2(0) = '1') else 
        x_2_V_read;
    select_ln86_8_fu_164_p3 <= 
        select_ln86_7_fu_150_p3 when (icmp_ln1496_8_fu_158_p2(0) = '1') else 
        select_ln86_fu_136_p3;
    select_ln86_9_fu_178_p3 <= 
        x_5_V_read when (icmp_ln1496_9_fu_172_p2(0) = '1') else 
        x_4_V_read;
    select_ln86_fu_136_p3 <= 
        x_1_V_read when (icmp_ln1496_fu_130_p2(0) = '1') else 
        x_0_V_read;
end behav;
