// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config13_s (
        ap_ready,
        data_2_V_read,
        data_4_V_read,
        data_6_V_read,
        data_7_V_read,
        data_8_V_read,
        data_9_V_read,
        data_10_V_read,
        ap_return_0,
        ap_return_1
);


output   ap_ready;
input  [26:0] data_2_V_read;
input  [26:0] data_4_V_read;
input  [26:0] data_6_V_read;
input  [26:0] data_7_V_read;
input  [26:0] data_8_V_read;
input  [26:0] data_9_V_read;
input  [26:0] data_10_V_read;
output  [26:0] ap_return_0;
output  [26:0] ap_return_1;

wire  signed [26:0] sext_ln1118_fu_76_p0;
wire  signed [26:0] shl_ln_fu_80_p1;
wire   [31:0] shl_ln_fu_80_p3;
wire   [31:0] sub_ln1118_fu_88_p2;
wire  signed [26:0] sext_ln1118_1_fu_104_p0;
wire  signed [26:0] shl_ln1118_s_fu_108_p1;
wire   [31:0] shl_ln1118_s_fu_108_p3;
wire  signed [31:0] sext_ln1118_1_fu_104_p1;
wire   [31:0] sub_ln1118_1_fu_116_p2;
wire  signed [26:0] sext_ln1118_2_fu_132_p0;
wire  signed [26:0] shl_ln1118_1_fu_136_p1;
wire   [31:0] shl_ln1118_1_fu_136_p3;
wire   [31:0] sub_ln1118_2_fu_144_p2;
wire  signed [26:0] sext_ln1118_3_fu_160_p0;
wire  signed [26:0] shl_ln1118_2_fu_164_p1;
wire   [31:0] shl_ln1118_2_fu_164_p3;
wire  signed [31:0] sext_ln1118_3_fu_160_p1;
wire   [31:0] sub_ln1118_3_fu_172_p2;
wire  signed [26:0] sext_ln1118_4_fu_188_p0;
wire  signed [26:0] shl_ln1118_3_fu_192_p1;
wire   [31:0] shl_ln1118_3_fu_192_p3;
wire  signed [31:0] sext_ln1118_4_fu_188_p1;
wire   [31:0] sub_ln1118_4_fu_200_p2;
wire  signed [26:0] sext_ln1118_5_fu_216_p0;
wire  signed [26:0] shl_ln1118_4_fu_220_p1;
wire   [31:0] shl_ln1118_4_fu_220_p3;
wire  signed [31:0] sext_ln1118_5_fu_216_p1;
wire   [31:0] sub_ln1118_5_fu_228_p2;
wire  signed [26:0] sext_ln1118_6_fu_244_p0;
wire  signed [26:0] shl_ln1118_5_fu_248_p1;
wire   [31:0] shl_ln1118_5_fu_248_p3;
wire  signed [31:0] sext_ln1118_6_fu_244_p1;
wire   [31:0] sub_ln1118_6_fu_256_p2;
wire   [26:0] trunc_ln708_s_fu_122_p4;
wire   [26:0] trunc_ln_fu_94_p4;
wire   [26:0] trunc_ln708_2_fu_178_p4;
wire   [26:0] trunc_ln708_1_fu_150_p4;
wire   [26:0] add_ln703_fu_272_p2;
wire   [26:0] add_ln703_1_fu_278_p2;
wire   [26:0] trunc_ln708_4_fu_234_p4;
wire   [26:0] trunc_ln708_3_fu_206_p4;
wire   [26:0] trunc_ln708_5_fu_262_p4;
wire   [26:0] add_ln703_3_fu_290_p2;
wire   [26:0] add_ln703_4_fu_296_p2;
wire   [26:0] add_ln703_2_fu_284_p2;
wire   [26:0] add_ln703_5_fu_302_p2;
wire  signed [31:0] sext_ln1118_fu_76_p1;
wire   [31:0] sub_ln1118_7_fu_314_p2;
wire   [31:0] sub_ln1118_8_fu_330_p2;
wire  signed [31:0] sext_ln1118_2_fu_132_p1;
wire   [31:0] sub_ln1118_9_fu_346_p2;
wire   [31:0] sub_ln1118_10_fu_362_p2;
wire   [31:0] sub_ln1118_11_fu_378_p2;
wire   [31:0] sub_ln1118_12_fu_394_p2;
wire   [31:0] sub_ln1118_13_fu_410_p2;
wire   [26:0] trunc_ln708_7_fu_336_p4;
wire   [26:0] trunc_ln708_6_fu_320_p4;
wire   [26:0] trunc_ln708_9_fu_368_p4;
wire   [26:0] trunc_ln708_8_fu_352_p4;
wire   [26:0] add_ln703_7_fu_426_p2;
wire   [26:0] add_ln703_8_fu_432_p2;
wire   [26:0] trunc_ln708_11_fu_400_p4;
wire   [26:0] trunc_ln708_10_fu_384_p4;
wire   [26:0] trunc_ln708_12_fu_416_p4;
wire   [26:0] add_ln703_10_fu_444_p2;
wire   [26:0] add_ln703_11_fu_450_p2;
wire   [26:0] add_ln703_9_fu_438_p2;
wire   [26:0] add_ln703_12_fu_456_p2;
wire   [26:0] add_ln703_6_fu_308_p2;
wire   [26:0] acc_1_V_fu_462_p2;

assign acc_1_V_fu_462_p2 = (add_ln703_9_fu_438_p2 + add_ln703_12_fu_456_p2);

assign add_ln703_10_fu_444_p2 = (trunc_ln708_11_fu_400_p4 + trunc_ln708_10_fu_384_p4);

assign add_ln703_11_fu_450_p2 = ($signed(trunc_ln708_12_fu_416_p4) + $signed(27'd134176768));

assign add_ln703_12_fu_456_p2 = (add_ln703_10_fu_444_p2 + add_ln703_11_fu_450_p2);

assign add_ln703_1_fu_278_p2 = (trunc_ln708_2_fu_178_p4 + trunc_ln708_1_fu_150_p4);

assign add_ln703_2_fu_284_p2 = (add_ln703_fu_272_p2 + add_ln703_1_fu_278_p2);

assign add_ln703_3_fu_290_p2 = (trunc_ln708_4_fu_234_p4 + trunc_ln708_3_fu_206_p4);

assign add_ln703_4_fu_296_p2 = (trunc_ln708_5_fu_262_p4 + 27'd40960);

assign add_ln703_5_fu_302_p2 = (add_ln703_3_fu_290_p2 + add_ln703_4_fu_296_p2);

assign add_ln703_6_fu_308_p2 = (add_ln703_2_fu_284_p2 + add_ln703_5_fu_302_p2);

assign add_ln703_7_fu_426_p2 = (trunc_ln708_7_fu_336_p4 + trunc_ln708_6_fu_320_p4);

assign add_ln703_8_fu_432_p2 = (trunc_ln708_9_fu_368_p4 + trunc_ln708_8_fu_352_p4);

assign add_ln703_9_fu_438_p2 = (add_ln703_7_fu_426_p2 + add_ln703_8_fu_432_p2);

assign add_ln703_fu_272_p2 = (trunc_ln708_s_fu_122_p4 + trunc_ln_fu_94_p4);

assign ap_ready = 1'b1;

assign ap_return_0 = add_ln703_6_fu_308_p2;

assign ap_return_1 = acc_1_V_fu_462_p2;

assign sext_ln1118_1_fu_104_p0 = data_4_V_read;

assign sext_ln1118_1_fu_104_p1 = sext_ln1118_1_fu_104_p0;

assign sext_ln1118_2_fu_132_p0 = data_6_V_read;

assign sext_ln1118_2_fu_132_p1 = sext_ln1118_2_fu_132_p0;

assign sext_ln1118_3_fu_160_p0 = data_7_V_read;

assign sext_ln1118_3_fu_160_p1 = sext_ln1118_3_fu_160_p0;

assign sext_ln1118_4_fu_188_p0 = data_8_V_read;

assign sext_ln1118_4_fu_188_p1 = sext_ln1118_4_fu_188_p0;

assign sext_ln1118_5_fu_216_p0 = data_9_V_read;

assign sext_ln1118_5_fu_216_p1 = sext_ln1118_5_fu_216_p0;

assign sext_ln1118_6_fu_244_p0 = data_10_V_read;

assign sext_ln1118_6_fu_244_p1 = sext_ln1118_6_fu_244_p0;

assign sext_ln1118_fu_76_p0 = data_2_V_read;

assign sext_ln1118_fu_76_p1 = sext_ln1118_fu_76_p0;

assign shl_ln1118_1_fu_136_p1 = data_6_V_read;

assign shl_ln1118_1_fu_136_p3 = {{shl_ln1118_1_fu_136_p1}, {5'd0}};

assign shl_ln1118_2_fu_164_p1 = data_7_V_read;

assign shl_ln1118_2_fu_164_p3 = {{shl_ln1118_2_fu_164_p1}, {5'd0}};

assign shl_ln1118_3_fu_192_p1 = data_8_V_read;

assign shl_ln1118_3_fu_192_p3 = {{shl_ln1118_3_fu_192_p1}, {5'd0}};

assign shl_ln1118_4_fu_220_p1 = data_9_V_read;

assign shl_ln1118_4_fu_220_p3 = {{shl_ln1118_4_fu_220_p1}, {5'd0}};

assign shl_ln1118_5_fu_248_p1 = data_10_V_read;

assign shl_ln1118_5_fu_248_p3 = {{shl_ln1118_5_fu_248_p1}, {5'd0}};

assign shl_ln1118_s_fu_108_p1 = data_4_V_read;

assign shl_ln1118_s_fu_108_p3 = {{shl_ln1118_s_fu_108_p1}, {5'd0}};

assign shl_ln_fu_80_p1 = data_2_V_read;

assign shl_ln_fu_80_p3 = {{shl_ln_fu_80_p1}, {5'd0}};

assign sub_ln1118_10_fu_362_p2 = (32'd0 - shl_ln1118_2_fu_164_p3);

assign sub_ln1118_11_fu_378_p2 = (32'd0 - shl_ln1118_3_fu_192_p3);

assign sub_ln1118_12_fu_394_p2 = (32'd0 - shl_ln1118_4_fu_220_p3);

assign sub_ln1118_13_fu_410_p2 = (32'd0 - shl_ln1118_5_fu_248_p3);

assign sub_ln1118_1_fu_116_p2 = ($signed(shl_ln1118_s_fu_108_p3) - $signed(sext_ln1118_1_fu_104_p1));

assign sub_ln1118_2_fu_144_p2 = (32'd0 - shl_ln1118_1_fu_136_p3);

assign sub_ln1118_3_fu_172_p2 = ($signed(shl_ln1118_2_fu_164_p3) - $signed(sext_ln1118_3_fu_160_p1));

assign sub_ln1118_4_fu_200_p2 = ($signed(shl_ln1118_3_fu_192_p3) - $signed(sext_ln1118_4_fu_188_p1));

assign sub_ln1118_5_fu_228_p2 = ($signed(shl_ln1118_4_fu_220_p3) - $signed(sext_ln1118_5_fu_216_p1));

assign sub_ln1118_6_fu_256_p2 = ($signed(shl_ln1118_5_fu_248_p3) - $signed(sext_ln1118_6_fu_244_p1));

assign sub_ln1118_7_fu_314_p2 = ($signed(shl_ln_fu_80_p3) - $signed(sext_ln1118_fu_76_p1));

assign sub_ln1118_8_fu_330_p2 = (32'd0 - shl_ln1118_s_fu_108_p3);

assign sub_ln1118_9_fu_346_p2 = ($signed(shl_ln1118_1_fu_136_p3) - $signed(sext_ln1118_2_fu_132_p1));

assign sub_ln1118_fu_88_p2 = (32'd0 - shl_ln_fu_80_p3);

assign trunc_ln708_10_fu_384_p4 = {{sub_ln1118_11_fu_378_p2[31:5]}};

assign trunc_ln708_11_fu_400_p4 = {{sub_ln1118_12_fu_394_p2[31:5]}};

assign trunc_ln708_12_fu_416_p4 = {{sub_ln1118_13_fu_410_p2[31:5]}};

assign trunc_ln708_1_fu_150_p4 = {{sub_ln1118_2_fu_144_p2[31:5]}};

assign trunc_ln708_2_fu_178_p4 = {{sub_ln1118_3_fu_172_p2[31:5]}};

assign trunc_ln708_3_fu_206_p4 = {{sub_ln1118_4_fu_200_p2[31:5]}};

assign trunc_ln708_4_fu_234_p4 = {{sub_ln1118_5_fu_228_p2[31:5]}};

assign trunc_ln708_5_fu_262_p4 = {{sub_ln1118_6_fu_256_p2[31:5]}};

assign trunc_ln708_6_fu_320_p4 = {{sub_ln1118_7_fu_314_p2[31:5]}};

assign trunc_ln708_7_fu_336_p4 = {{sub_ln1118_8_fu_330_p2[31:5]}};

assign trunc_ln708_8_fu_352_p4 = {{sub_ln1118_9_fu_346_p2[31:5]}};

assign trunc_ln708_9_fu_368_p4 = {{sub_ln1118_10_fu_362_p2[31:5]}};

assign trunc_ln708_s_fu_122_p4 = {{sub_ln1118_1_fu_116_p2[31:5]}};

assign trunc_ln_fu_94_p4 = {{sub_ln1118_fu_88_p2[31:5]}};

endmodule //dense_wrapper_ap_fixed_ap_fixed_27_9_5_3_0_config13_s
