AcceleratorConfig:
  Board: alveo-u250
  Driver: python
  Interface: axi_stream
  Platform: xilinx_u250_xdma_201830_2
  Precision:
    Input: ap_uint<1024>
    Output: ap_fixed<1024, 1006>
Backend: VivadoAccelerator
ClockPeriod: 5
HLSConfig:
  LayerName:
    input_1:
      Precision: ap_ufixed<12, 0>
      Trace: true
    max_pooling2d:
      Precision: ap_fixed<27, 9>
      Trace: true
    max_pooling2d_1:
      Precision: ap_fixed<27, 9>
      Trace: true
    output:
      Precision:
        bias: ap_fixed<6,1>
        weight: ap_fixed<6,1>
      ReuseFactor: 1
      Trace: true
    output_linear:
      Precision: ap_fixed<1024, 1006>
      ReuseFactor: 1
      Trace: true
      table_size: 1024
      table_t: ap_fixed<18,8>
    q_conv2d:
      Precision:
        bias: ap_fixed<16,9>
        weight: ap_fixed<6,1>
      ReuseFactor: 1
      Trace: true
    q_conv2d_1:
      Precision:
        bias: ap_fixed<16,9>
        weight: ap_fixed<6,1>
      ReuseFactor: 1
      Trace: true
    q_conv2d_1_linear:
      Precision: ap_fixed<27, 9>
      ReuseFactor: 1
      Trace: true
      table_size: 1024
      table_t: ap_fixed<18,8>
    q_conv2d_linear:
      Precision: ap_fixed<27, 9>
      ReuseFactor: 1
      Trace: true
      table_size: 1024
      table_t: ap_fixed<18,8>
    q_dense:
      Precision:
        bias: ap_fixed<6,1>
        weight: ap_fixed<6,1>
      ReuseFactor: 1
      Trace: true
    q_dense_linear:
      Precision: ap_fixed<27, 9>
      ReuseFactor: 1
      Trace: true
      table_size: 1024
      table_t: ap_fixed<18,8>
    sum_pooling2d:
      Precision: ap_ufixed<16, 4>
      Trace: true
    zero_padding2d:
      Precision: ap_ufixed<12, 0>
      Trace: true
  Model:
    Precision: ap_fixed<27, 9>
    ReuseFactor: 1
    Strategy: Resource
IOType: io_stream
InputData: null
KerasModel: !keras_model '/mnt/storage1/akshaymalige/demo_new/rt_detect_le_events_dune-main/out/classifier_2d_s544_o2_i64_480_1_c32_64_1_q/le/hls4ml_prj_u250_custom_stream_axi_fused_fixed_1024_1024_12/keras_model.h5'
OutputDir: /mnt/storage1/akshaymalige/demo_new/rt_detect_le_events_dune-main/out/classifier_2d_s544_o2_i64_480_1_c32_64_1_q/le/hls4ml_prj_u250_custom_stream_axi_fused_fixed_1024_1024_12
OutputPredictions: null
Part: xcu250-figd2104-2L-e
ProjectName: myproject
Stamp: faBc56AE
